[package]
name = "vane"
version = "1.0.0"
edition = "2024"
description = "A lightweight static resource server built with axum."
license = "MIT"
repository = "https://github.com/canmi21/vane"
readme = "README.md"
keywords = ["network", "server", "web", "vane", "axum"]
categories = ["network-programming", "web-programming", "development-tools"]

[[bin]]
name = "vane"
path = "src/main.rs"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5", features = ["fs"] }
dotenvy = "0.15"
fancy-log = "0.1"
shellexpand = "3"
anyhow = "1"
lazy-motd = "1"
chrono = "0.4"
serde = "1"
serde_json = "1"
path-clean = "1"
tower = { version = "0.5", features = ["full"] }
percent-encoding = "2"