[package]
name = "vane"
version = "1.2.3"
edition = "2024"
description = "Vane is a minimal reverse proxy in Rust with domain-based routing, wildcard support, and automatic SSL via ACME."
license = "MIT"
repository = "https://github.com/canmi21/vane"
readme = "README.md"
keywords = ["network", "server", "web", "vane", "proxy"]
categories = ["network-programming", "web-programming", "development-tools"]

[[bin]]
name = "vane"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full", "signal"] }
axum = { version = "0.8", features = ["macros"] }
axum-server = { version = "0.7", features = ["tls-rustls-no-provider"] }
axum-extra = { version = "0.10", features = ["typed-header"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tower = { version = "0.5", features = ["full"] }
tower-http = { version = "0.5", features = ["fs", "trace", "cors"] }
rustls = { version = "0.23", features = ["ring", "aws-lc-rs"] }
rustls-pemfile = "2"
base64 = "0.22"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
hyper = { version = "1", features = ["full"] }
hyper-rustls = { version = "0.27", features = ["webpki-roots", "http2"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
dotenvy = "0.15"
fancy-log = "0.1"
shellexpand = "3"
anyhow = "1"
lazy-motd = "1"
chrono = "0.4"
path-clean = "1"
percent-encoding = "2"
headers = "0.4"
toml = "0.9"
webpki-roots = "1"
rcgen = "0.14"
h3 = "0.0.8"
h3-quinn = "0.0.10"
quinn = { version = "0.11", features = ["rustls"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
bytes = "1"
http = "1"
include_dir = "0.7"
lazy-limit = "1"
governor = "0.10"
nonzero = "0.2"