[graph]
exclude-unpublished = true

[advisories]
unmaintained = "none"
ignore = []

[licenses]
confidence-threshold = 0.8
allow = [
		"CC0-1.0",
		"ISC",
		"MIT",
    "Apache-2.0",
    "BSD-3-Clause",
		"MPL-2.0",
    "Unicode-3.0",
		"CDLA-Permissive-2.0",
]

[bans]
multiple-versions = "deny"
highlight = "all"
skip-tree = [
    # currently duplicated through header, reqwest, tower-http and cookie
    { name = "base64" },
    # parking_lot pulls in old versions of windows-sys
    { name = "windows-sys" },
		{ name = "winapi" },
		{ name = "windows-core" },
		{ name = "windows-result" },
		{ name = "windows-strings" },
    # pulled in by quickcheck and cookie
    { name = "rand" },
		{ name = "bitflags" },
		{ name = "hashbrown" },
		{ name = "http" },
		{ name = "http-body" },
		{ name = "hyper" },
		{ name = "hyper-rustls" },
		{ name = "idna" },
		{ name = "reqwest" },
		{ name = "rustls" },
		{ name = "rustls-webpki" },
		{ name = "socket2" },
		{ name = "sync_wrapper" },
		{ name = "thiserror" },
		{ name = "thiserror-impl" },
		{ name = "tokio-rustls" },
		{ name = "webpki-roots" },
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-git = []