services:
  vane:
    image: canmi/vane:latest
    container_name: vane
    networks:
      - internal
    env_file:
      - ./.env
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - /opt/vane:/root/vane
    restart: unless-stopped

networks:
  internal:
    driver: bridge