# tests/test_suite.py

"""
This module acts as the central registry for all test cases in the suite.

To add a new test, you only need to modify this file:
1.  Add the import statement for your new test module.
2.  Add a new tuple `("module.name", module.run_function)` to the TEST_SUITE list
    at the desired position.
"""

from units import (
    test_env_loglevel,
    test_socket_dir,
    test_console,
    test_port_cold_load,
    test_port_hot_unload,
    test_port_hot_reload,
    test_config_formats_toml_yaml,
    test_config_formats_json_toml,
    test_config_formats_yaml_json,
    test_dynamic_port,
    test_multi_port_binding,
    test_tcp_proxy,
    test_tcp_filtering,
    test_mix_port_forwarding,
    test_protocol_priority,
    test_duplicate_configs,
    test_invalid_json,
    test_invalid_toml,
    test_invalid_yaml,
    test_strategy_serial,
    test_strategy_random,
    test_strategy_fastest,
    test_no_available_targets,
    test_routing_to_single_available_target,
    test_serial_strategy_with_runtime_failure,
    test_backend_auto_recovery,
    test_fallback_routing,
    test_fallback_auto_recovery,
    test_capture_all_fallback,
    test_udp_proxy,
    test_udp_fallback,
    test_udp_single_client_burst,
    test_udp_strategy_serial,
    test_udp_mix_port_forwarding,
    test_listen_dual_stack,
    test_node_forwarding,
    test_domain_forwarding,
    test_custom_resolver,
    test_flow_engine_basic,
    test_flow_engine_udp,
    test_logic_hot_reload,
    test_flow_ratelimit,
    test_external_plugin_registration,
    test_external_plugin_persistence,
    test_external_plugin_exec_flow,
    test_external_plugin_c,
    test_external_plugin_cpp,
    test_external_plugin_go,
    test_external_plugin_rust,
    test_external_plugin_zig,
    test_external_plugin_python,
    test_external_plugin_node,
    test_external_plugin_ruby,
    test_external_plugin_lua,
    test_external_plugin_shell,
    test_external_plugin_java,
    test_external_plugin_exec_failure,
    test_external_plugin_exec_env,
    test_external_plugin_httpx,
    test_external_plugin_unix,
    test_proxy_node,
    test_proxy_domain,
    test_flow_engine_tls,
    test_flow_engine_quic,
)

# The master list of all tests to be executed sequentially. This is the single
# source of truth for the test suite's content and order.
TEST_SUITE = [
    ("units.test_env_loglevel", test_env_loglevel.run),
    ("units.test_socket_dir", test_socket_dir.run),
    ("units.test_console", test_console.run),
    ("units.test_port_cold_load", test_port_cold_load.run),
    ("units.test_port_hot_unload", test_port_hot_unload.run),
    ("units.test_port_hot_reload", test_port_hot_reload.run),
    ("units.test_config_formats_toml_yaml", test_config_formats_toml_yaml.run),
    ("units.test_config_formats_json_toml", test_config_formats_json_toml.run),
    ("units.test_config_formats_yaml_json", test_config_formats_yaml_json.run),
    ("units.test_dynamic_port", test_dynamic_port.run),
    ("units.test_multi_port_binding", test_multi_port_binding.run),
    ("units.test_tcp_proxy", test_tcp_proxy.run),
    ("units.test_tcp_filtering", test_tcp_filtering.run),
    ("units.test_mix_port_forwarding", test_mix_port_forwarding.run),
    ("units.test_protocol_priority", test_protocol_priority.run),
    ("units.test_duplicate_configs", test_duplicate_configs.run),
    ("units.test_invalid_json", test_invalid_json.run),
    ("units.test_invalid_toml", test_invalid_toml.run),
    ("units.test_invalid_yaml", test_invalid_yaml.run),
    ("units.test_strategy_serial", test_strategy_serial.run),
    ("units.test_strategy_random", test_strategy_random.run),
    ("units.test_strategy_fastest", test_strategy_fastest.run),
    ("units.test_no_available_targets", test_no_available_targets.run),
    (
        "units.test_routing_to_single_available_target",
        test_routing_to_single_available_target.run,
    ),
    (
        "units.test_serial_strategy_with_runtime_failure",
        test_serial_strategy_with_runtime_failure.run,
    ),
    ("units.test_backend_auto_recovery", test_backend_auto_recovery.run),
    ("units.test_fallback_routing", test_fallback_routing.run),
    ("units.test_fallback_auto_recovery", test_fallback_auto_recovery.run),
    ("units.test_capture_all_fallback", test_capture_all_fallback.run),
    ("units.test_udp_proxy", test_udp_proxy.run),
    ("units.test_udp_fallback", test_udp_fallback.run),
    ("units.test_udp_single_client_burst", test_udp_single_client_burst.run),
    ("units.test_udp_strategy_serial", test_udp_strategy_serial.run),
    ("units.test_udp_mix_port_forwarding", test_udp_mix_port_forwarding.run),
    ("units.test_listen_dual_stack", test_listen_dual_stack.run),
    ("units.test_node_forwarding", test_node_forwarding.run),
    ("units.test_domain_forwarding", test_domain_forwarding.run),
    ("units.test_custom_resolver", test_custom_resolver.run),
    ("units.test_flow_engine_basic", test_flow_engine_basic.run),
    ("units.test_flow_engine_udp", test_flow_engine_udp.run),
    ("units.test_logic_hot_reload", test_logic_hot_reload.run),
    ("units.test_flow_ratelimit", test_flow_ratelimit.run),
    ("units.test_external_plugin_registration", test_external_plugin_registration.run),
    ("units.test_external_plugin_persistence", test_external_plugin_persistence.run),
    ("units.test_external_plugin_exec_flow", test_external_plugin_exec_flow.run),
    ("units.test_external_plugin_c", test_external_plugin_c.run),
    ("units.test_external_plugin_cpp", test_external_plugin_cpp.run),
    ("units.test_external_plugin_go", test_external_plugin_go.run),
    ("units.test_external_plugin_rust", test_external_plugin_rust.run),
    ("units.test_external_plugin_zig", test_external_plugin_zig.run),
    ("units.test_external_plugin_python", test_external_plugin_python.run),
    ("units.test_external_plugin_node", test_external_plugin_node.run),
    ("units.test_external_plugin_ruby", test_external_plugin_ruby.run),
    ("units.test_external_plugin_lua", test_external_plugin_lua.run),
    ("units.test_external_plugin_shell", test_external_plugin_shell.run),
    ("units.test_external_plugin_java", test_external_plugin_java.run),
    ("units.test_external_plugin_exec_failure", test_external_plugin_exec_failure.run),
    ("units.test_external_plugin_exec_env", test_external_plugin_exec_env.run),
    ("units.test_external_plugin_httpx", test_external_plugin_httpx.run),
    ("units.test_external_plugin_unix", test_external_plugin_unix.run),
    ("units.test_proxy_node", test_proxy_node.run),
    ("units.test_proxy_domain", test_proxy_domain.run),
    ("units.test_flow_engine_tls", test_flow_engine_tls.run),
    ("units.test_flow_engine_quic", test_flow_engine_quic.run),
]
