[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
ar = "x86_64-linux-musl-ar"

[alias]
c = "check --all-targets --workspace"
b = "build --all-targets --workspace"
t = "test --workspace"
lint = "clippy --workspace --all-targets -- -D warnings"
ci = "test --workspace --all-features"
xtask = "run --quiet --package xtask --"
