/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SslIndexRouteImport } from './routes/ssl/index'
import { Route as RatelimitIndexRouteImport } from './routes/ratelimit/index'
import { Route as ModulesIndexRouteImport } from './routes/modules/index'
import { Route as DomainsIndexRouteImport } from './routes/domains/index'
import { Route as CorsIndexRouteImport } from './routes/cors/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SslIndexRoute = SslIndexRouteImport.update({
  id: '/ssl/',
  path: '/ssl/',
  getParentRoute: () => rootRouteImport,
} as any)
const RatelimitIndexRoute = RatelimitIndexRouteImport.update({
  id: '/ratelimit/',
  path: '/ratelimit/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesIndexRoute = ModulesIndexRouteImport.update({
  id: '/modules/',
  path: '/modules/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsIndexRoute = DomainsIndexRouteImport.update({
  id: '/domains/',
  path: '/domains/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorsIndexRoute = CorsIndexRouteImport.update({
  id: '/cors/',
  path: '/cors/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cors': typeof CorsIndexRoute
  '/domains': typeof DomainsIndexRoute
  '/modules': typeof ModulesIndexRoute
  '/ratelimit': typeof RatelimitIndexRoute
  '/ssl': typeof SslIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cors': typeof CorsIndexRoute
  '/domains': typeof DomainsIndexRoute
  '/modules': typeof ModulesIndexRoute
  '/ratelimit': typeof RatelimitIndexRoute
  '/ssl': typeof SslIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cors/': typeof CorsIndexRoute
  '/domains/': typeof DomainsIndexRoute
  '/modules/': typeof ModulesIndexRoute
  '/ratelimit/': typeof RatelimitIndexRoute
  '/ssl/': typeof SslIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cors' | '/domains' | '/modules' | '/ratelimit' | '/ssl'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cors' | '/domains' | '/modules' | '/ratelimit' | '/ssl'
  id:
    | '__root__'
    | '/'
    | '/cors/'
    | '/domains/'
    | '/modules/'
    | '/ratelimit/'
    | '/ssl/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CorsIndexRoute: typeof CorsIndexRoute
  DomainsIndexRoute: typeof DomainsIndexRoute
  ModulesIndexRoute: typeof ModulesIndexRoute
  RatelimitIndexRoute: typeof RatelimitIndexRoute
  SslIndexRoute: typeof SslIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssl/': {
      id: '/ssl/'
      path: '/ssl'
      fullPath: '/ssl'
      preLoaderRoute: typeof SslIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratelimit/': {
      id: '/ratelimit/'
      path: '/ratelimit'
      fullPath: '/ratelimit'
      preLoaderRoute: typeof RatelimitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/': {
      id: '/modules/'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/': {
      id: '/domains/'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cors/': {
      id: '/cors/'
      path: '/cors'
      fullPath: '/cors'
      preLoaderRoute: typeof CorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CorsIndexRoute: CorsIndexRoute,
  DomainsIndexRoute: DomainsIndexRoute,
  ModulesIndexRoute: ModulesIndexRoute,
  RatelimitIndexRoute: RatelimitIndexRoute,
  SslIndexRoute: SslIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
