//! vane WASM plugin runtime: wasmtime + Component Model + instance pooling + host functions.
//!
//! See `spec/architecture/11-wasm.md`.

#![allow(unsafe_code)] // Component::deserialize_file is unsafe per wasmtime API

use std::path::Path;
use std::sync::Arc;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use rand::Rng;
use sha2::{Digest, Sha256};
use tracing::{trace, warn};
use wasmtime::component::{Component, HasSelf, Linker};
use wasmtime::{Config, Engine, PoolingAllocationConfig, Store};

use vane_core::middleware::MiddlewareKind;
use vane_core::{
	Error, HttpFetchBackend, HttpFetchError, HttpFetchLimits, HttpFetchRequest, PluginExport,
	PluginMetadata, WasmRuntime,
};

// Generate host-side bindings from the WIT world. This produces:
//   - `Plugin` struct (instantiated component accessor)
//   - `vane::host::host::Host` trait (host import implementations, RPITIT async)
//   - `Plugin::add_to_linker` for wiring host functions
wasmtime::component::bindgen!({
		path: "wit",
		world: "plugin",
		imports: {
				default: async | trappable,
		},
});

// ─── host state ──────────────────────────────────────────────────────────────

/// Per-Store state threaded through every host function call.
struct HostState {
	args: String,
	fetch_backend: Arc<dyn HttpFetchBackend>,
}

// vane:plugin/types has no functions; the generated Host trait is empty.
impl vane::plugin::types::Host for HostState {}

// Implement the host import trait generated by `bindgen!`.
// Native async fn is used (RPITIT, no #[async_trait]).
impl vane::host::host::Host for HostState {
	async fn get_args(&mut self) -> wasmtime::Result<String> {
		Ok(self.args.clone())
	}

	async fn log(
		&mut self,
		level: vane::host::host::LogLevel,
		message: String,
		fields: Vec<vane::host::host::LogField>,
	) -> wasmtime::Result<()> {
		use vane::host::host::LogLevel;
		let kv: String = fields.iter().fold(String::new(), |mut s, f| {
			use std::fmt::Write as _;
			let _ = write!(s, " {}={}", f.key, f.value);
			s
		});
		match level {
			LogLevel::Trace => trace!(plugin = true, "{message}{kv}"),
			LogLevel::Debug => tracing::debug!(plugin = true, "{message}{kv}"),
			LogLevel::Info => tracing::info!(plugin = true, "{message}{kv}"),
			LogLevel::Warn => warn!(plugin = true, "{message}{kv}"),
			LogLevel::Error => tracing::error!(plugin = true, "{message}{kv}"),
		}
		Ok(())
	}

	async fn now_unix_ms(&mut self) -> wasmtime::Result<u64> {
		let d = SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default();
		Ok(d.as_secs() * 1000 + u64::from(d.subsec_millis()))
	}

	async fn random(&mut self, buf_len: u32) -> wasmtime::Result<Vec<u8>> {
		let mut buf = vec![0u8; buf_len as usize];
		rand::rng().fill_bytes(&mut buf);
		Ok(buf)
	}

	async fn metric_counter(
		&mut self,
		_name: String,
		_delta: u64,
		_labels: Vec<vane::host::host::MetricLabel>,
	) -> wasmtime::Result<()> {
		// TODO(wasm-metrics): route to daemon metrics facade
		Ok(())
	}

	async fn metric_gauge(
		&mut self,
		_name: String,
		_value: i64,
		_labels: Vec<vane::host::host::MetricLabel>,
	) -> wasmtime::Result<()> {
		// TODO(wasm-metrics): route to daemon metrics facade
		Ok(())
	}

	async fn http_fetch(
		&mut self,
		req: vane::host::host::HttpFetchRequest,
	) -> wasmtime::Result<Result<vane::host::host::HttpFetchResponse, vane::host::host::NetError>> {
		let vane_req = HttpFetchRequest {
			method: req.method,
			url: req.url,
			headers: req.headers,
			body: req.body,
			timeout_ms: req.timeout_ms,
			follow_redirects: req.follow_redirects,
			verify_tls: req.verify_tls,
		};
		let limits = HttpFetchLimits::default();
		match self.fetch_backend.fetch(vane_req, limits).await {
			Ok(resp) => Ok(Ok(vane::host::host::HttpFetchResponse {
				status: resp.status,
				headers: resp.headers,
				body: resp.body,
			})),
			Err(e) => Ok(Err(map_fetch_error(e))),
		}
	}
}

fn map_fetch_error(e: HttpFetchError) -> vane::host::host::NetError {
	use vane::host::host::NetError;
	match e {
		HttpFetchError::DnsFailure(s) => NetError::DnsFailure(s),
		HttpFetchError::ConnectionRefused => NetError::ConnectionRefused,
		HttpFetchError::Timeout => NetError::Timeout,
		HttpFetchError::TlsError(s) => NetError::TlsError(s),
		HttpFetchError::PoolExhausted => NetError::PoolExhausted,
		HttpFetchError::BodyTooLarge => NetError::BodyTooLarge,
		HttpFetchError::NotAllowed(s) => NetError::NotAllowed(s),
		HttpFetchError::InsecureRejected => NetError::InsecureRejected,
		HttpFetchError::Internal(s) => NetError::Internal(s),
	}
}

// ─── WasmtimeRuntime ─────────────────────────────────────────────────────────

/// Expected ABI major version. Components whose `abi-version` has a different
/// major component are rejected at load time.
const ABI_MAJOR: u64 = 0;

/// Path to the compiled component cache.
const CWASM_CACHE_DIR: &str = "/var/lib/vaned/wasm";

pub struct WasmtimeRuntime {
	engine: Engine,
	fetch_backend: Arc<dyn HttpFetchBackend>,
	epoch_abort: tokio::task::AbortHandle,
}

impl Drop for WasmtimeRuntime {
	fn drop(&mut self) {
		self.epoch_abort.abort();
	}
}

impl WasmtimeRuntime {
	/// Construct a new runtime. Starts the 1 ms epoch ticker immediately.
	///
	/// # Errors
	///
	/// Fails if wasmtime cannot build the pooling engine (unsupported platform
	/// or configuration conflict).
	pub fn new(fetch_backend: Arc<dyn HttpFetchBackend>) -> Result<Arc<Self>, Error> {
		let engine = build_engine().map_err(|e| Error::internal(e.to_string()))?;

		let ticker_engine = engine.clone();
		let handle = tokio::spawn(async move {
			let mut interval = tokio::time::interval(Duration::from_millis(1));
			interval.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);
			loop {
				interval.tick().await;
				ticker_engine.increment_epoch();
			}
		});
		let epoch_abort = handle.abort_handle();

		Ok(Arc::new(Self { engine, fetch_backend, epoch_abort }))
	}
}

#[async_trait::async_trait]
impl WasmRuntime for WasmtimeRuntime {
	async fn load_component(&self, path: &Path) -> Result<Arc<PluginMetadata>, Error> {
		let bytes =
			std::fs::read(path).map_err(|e| Error::internal(format!("read {}: {e}", path.display())))?;

		let hash = hex_sha256(&bytes);
		let cwasm_path = std::path::PathBuf::from(CWASM_CACHE_DIR).join(format!("{hash}.cwasm"));

		let component = load_or_compile(&self.engine, path, &cwasm_path, &bytes)?;
		let meta = get_metadata(&self.engine, &component, Arc::clone(&self.fetch_backend)).await?;
		validate_handler_exports(&self.engine, &component, &meta.exports)?;
		Ok(meta)
	}
}

// ─── engine construction ─────────────────────────────────────────────────────

fn build_engine() -> wasmtime::Result<Engine> {
	let mut config = Config::new();
	config.epoch_interruption(true);

	// 1 MiB per instance; 32 instances daemon-wide cap for stateless plugins.
	let mut pool = PoolingAllocationConfig::default();
	pool.max_memory_size(1024 * 1024);
	pool.total_memories(32);
	pool.total_component_instances(32);
	config.allocation_strategy(pool);

	Engine::new(&config)
}

// ─── component loading ───────────────────────────────────────────────────────

fn hex_sha256(data: &[u8]) -> String {
	let mut h = Sha256::new();
	h.update(data);
	h.finalize().iter().fold(String::new(), |mut s, b| {
		use std::fmt::Write as _;
		let _ = write!(s, "{b:02x}");
		s
	})
}

fn load_or_compile(
	engine: &Engine,
	src: &Path,
	cache: &Path,
	bytes: &[u8],
) -> Result<Component, Error> {
	if cache.exists() {
		match unsafe { Component::deserialize_file(engine, cache) } {
			Ok(c) => {
				trace!("wasm cache hit: {cache:?}");
				return Ok(c);
			}
			Err(e) => {
				warn!("wasm cache deserialize failed, recompiling: {e}");
			}
		}
	}

	let component = Component::from_binary(engine, bytes)
		.map_err(|e| Error::internal(format!("compile {}: {e}", src.display())))?;

	if let Ok(()) = std::fs::create_dir_all(CWASM_CACHE_DIR) {
		match component.serialize() {
			Ok(cwasm) => {
				if let Err(e) = std::fs::write(cache, &cwasm) {
					warn!("wasm cache write failed ({cache:?}): {e}");
				}
			}
			Err(e) => warn!("wasm serialize failed: {e}"),
		}
	}

	Ok(component)
}

// ─── metadata extraction ─────────────────────────────────────────────────────

async fn get_metadata(
	engine: &Engine,
	component: &Component,
	fetch_backend: Arc<dyn HttpFetchBackend>,
) -> Result<Arc<PluginMetadata>, Error> {
	let mut linker = Linker::<HostState>::new(engine);
	Plugin::add_to_linker::<HostState, HasSelf<HostState>>(&mut linker, |x| x)
		.map_err(|e| Error::internal(format!("linker setup: {e}")))?;

	let host_state = HostState { args: String::new(), fetch_backend };
	let mut store = Store::new(engine, host_state);
	// Allow up to 1000 ticks (≈1 s at 1 ms interval) for metadata loading.
	store.set_epoch_deadline(1000);

	let plugin = Plugin::instantiate_async(&mut store, component, &linker)
		.await
		.map_err(|e| Error::internal(format!("instantiate: {e}")))?;

	let raw = plugin
		.vane_plugin_registry()
		.call_get_metadata(&mut store)
		.map_err(|e| Error::internal(format!("get-metadata: {e}")))?;

	parse_metadata(raw)
}

// ─── handler-kind validation ─────────────────────────────────────────────────

// For each metadata export claiming kind K, confirm the component actually
// exports the corresponding handler interface at the component type level.
// This runs before any instantiation so the check is purely type-level.
fn validate_handler_exports(
	engine: &Engine,
	component: &Component,
	exports: &[PluginExport],
) -> Result<(), Error> {
	let comp_type = component.component_type();
	for export in exports {
		let iface = match export.kind {
			MiddlewareKind::L4Peek => "vane:plugin/handler-l4-peek@0.1.0",
			MiddlewareKind::L4Bytes => "vane:plugin/handler-l4-bytes@0.1.0",
			MiddlewareKind::L7Request => "vane:plugin/handler-l7-request@0.1.0",
			MiddlewareKind::L7Response => "vane:plugin/handler-l7-response@0.1.0",
		};
		if comp_type.get_export(engine, iface).is_none() {
			return Err(Error::internal(format!(
				"export '{}' declares kind '{}' but component does not export handler interface '{iface}'",
				export.name,
				kind_str(export.kind),
			)));
		}
	}
	Ok(())
}

fn kind_str(kind: MiddlewareKind) -> &'static str {
	match kind {
		MiddlewareKind::L4Peek => "l4-peek",
		MiddlewareKind::L4Bytes => "l4-bytes",
		MiddlewareKind::L7Request => "l7-request",
		MiddlewareKind::L7Response => "l7-response",
	}
}

fn parse_metadata(
	raw: exports::vane::plugin::registry::Metadata,
) -> Result<Arc<PluginMetadata>, Error> {
	// Validate abi-version major == ABI_MAJOR (0).
	let abi = &raw.abi_version;
	let major =
		abi.split('.').next().and_then(|s| s.parse::<u64>().ok()).ok_or_else(|| {
			Error::internal(format!("abi-version '{abi}' is not a valid semver string"))
		})?;
	if major != ABI_MAJOR {
		return Err(Error::internal(format!(
			"abi-version '{abi}' major {major} != expected {ABI_MAJOR}"
		)));
	}

	// Reject any export with needs-streaming-body: true.
	for exp in &raw.exports {
		if exp.needs_streaming_body {
			return Err(Error::internal(format!(
				"export '{}' sets needs-streaming-body: true, which is reserved in 0.1.0",
				exp.name
			)));
		}
	}

	// Reject duplicate export names.
	let mut seen = std::collections::HashSet::new();
	for exp in &raw.exports {
		if !seen.insert(exp.name.as_str()) {
			return Err(Error::internal(format!("duplicate export name '{}' in metadata", exp.name)));
		}
	}

	let exports = raw
		.exports
		.into_iter()
		.map(|e| {
			let kind = match e.kind {
				vane::plugin::types::MiddlewareKind::L4Peek => MiddlewareKind::L4Peek,
				vane::plugin::types::MiddlewareKind::L4Bytes => MiddlewareKind::L4Bytes,
				vane::plugin::types::MiddlewareKind::L7Request => MiddlewareKind::L7Request,
				vane::plugin::types::MiddlewareKind::L7Response => MiddlewareKind::L7Response,
			};
			PluginExport {
				name: e.name,
				kind,
				stateless: e.stateless,
				needs_body: e.needs_body,
				inspects: e.inspects,
			}
		})
		.collect();

	Ok(Arc::new(PluginMetadata {
		name: raw.name,
		version: raw.version,
		abi_version: raw.abi_version,
		exports,
	}))
}

// ─── tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
	use super::*;
	use async_trait::async_trait;

	struct MockFetch;

	#[async_trait]
	impl HttpFetchBackend for MockFetch {
		async fn fetch(
			&self,
			_req: HttpFetchRequest,
			_limits: HttpFetchLimits,
		) -> Result<vane_core::HttpFetchResponse, HttpFetchError> {
			Err(HttpFetchError::Internal("test".into()))
		}
	}

	fn mock_backend() -> Arc<dyn HttpFetchBackend> {
		Arc::new(MockFetch)
	}

	// Verify the Engine builds and the epoch ticker starts without panicking.
	// This exercises `build_engine` + the tokio::spawn path inside `new`.
	#[tokio::test]
	async fn runtime_new_constructs_engine_and_starts_ticker() {
		let rt = WasmtimeRuntime::new(mock_backend()).expect("WasmtimeRuntime::new");
		// Yield to let the ticker task run at least once.
		tokio::time::sleep(Duration::from_millis(5)).await;
		// The epoch counter is an internal Engine state; we can't read it directly,
		// but if the ticker panicked the task would be aborted and `rt` would still
		// be valid (abort_handle is already set). Existence of `rt` is enough.
		drop(rt);
	}

	// load_component must return a typed error for a missing file.
	#[tokio::test]
	async fn load_component_missing_file_returns_error() {
		let rt = WasmtimeRuntime::new(mock_backend()).expect("runtime");
		let err =
			rt.load_component(Path::new("/nonexistent/plugin.wasm")).await.expect_err("must fail");
		assert!(err.to_string().contains("read"), "error should mention read: {err}");
	}

	// load_component must return a typed error for a file that is not a WASM component.
	#[tokio::test]
	async fn load_component_invalid_bytes_returns_error() {
		let dir = tempfile::tempdir().expect("tempdir");
		let path = dir.path().join("bad.wasm");
		std::fs::write(&path, b"not wasm at all").expect("write");
		let rt = WasmtimeRuntime::new(mock_backend()).expect("runtime");
		let err = rt.load_component(&path).await.expect_err("must fail");
		assert!(err.to_string().contains("compile"), "error should mention compile: {err}");
	}

	// parse_metadata rejects an abi-version with wrong major.
	#[test]
	fn parse_metadata_rejects_wrong_abi_major() {
		let raw = exports::vane::plugin::registry::Metadata {
			name: "test".into(),
			version: "1.0.0".into(),
			abi_version: "1.0.0".into(), // major=1, expected 0
			exports: vec![],
		};
		let err = parse_metadata(raw).expect_err("must reject");
		assert!(err.to_string().contains("major"), "{err}");
	}

	// parse_metadata rejects needs-streaming-body: true.
	#[test]
	fn parse_metadata_rejects_streaming_body() {
		let raw = exports::vane::plugin::registry::Metadata {
			name: "test".into(),
			version: "1.0.0".into(),
			abi_version: "0.1.0".into(),
			exports: vec![vane::plugin::types::MiddlewareExport {
				name: "e".into(),
				kind: vane::plugin::types::MiddlewareKind::L7Request,
				stateless: true,
				needs_body: false,
				inspects: vec![],
				needs_streaming_body: true,
			}],
		};
		let err = parse_metadata(raw).expect_err("must reject");
		assert!(err.to_string().contains("streaming"), "{err}");
	}

	// parse_metadata rejects duplicate export names.
	#[test]
	fn parse_metadata_rejects_duplicate_export_names() {
		let export = || vane::plugin::types::MiddlewareExport {
			name: "dup".into(),
			kind: vane::plugin::types::MiddlewareKind::L7Request,
			stateless: true,
			needs_body: false,
			inspects: vec![],
			needs_streaming_body: false,
		};
		let raw = exports::vane::plugin::registry::Metadata {
			name: "test".into(),
			version: "1.0.0".into(),
			abi_version: "0.1.0".into(),
			exports: vec![export(), export()],
		};
		let err = parse_metadata(raw).expect_err("must reject");
		assert!(err.to_string().contains("duplicate"), "{err}");
	}

	// parse_metadata correctly maps all four MiddlewareKind variants.
	#[test]
	fn parse_metadata_maps_all_middleware_kinds() {
		use vane::plugin::types::MiddlewareKind as WitKind;
		for (wit, expected) in [
			(WitKind::L4Peek, MiddlewareKind::L4Peek),
			(WitKind::L4Bytes, MiddlewareKind::L4Bytes),
			(WitKind::L7Request, MiddlewareKind::L7Request),
			(WitKind::L7Response, MiddlewareKind::L7Response),
		] {
			let raw = exports::vane::plugin::registry::Metadata {
				name: "p".into(),
				version: "0.1.0".into(),
				abi_version: "0.1.0".into(),
				exports: vec![vane::plugin::types::MiddlewareExport {
					name: "e".into(),
					kind: wit,
					stateless: true,
					needs_body: false,
					inspects: vec![],
					needs_streaming_body: false,
				}],
			};
			let meta = parse_metadata(raw).expect("parse");
			assert_eq!(meta.exports[0].kind, expected);
		}
	}

	// Smoke test: load the fixture component generated by build.rs and verify
	// that the metadata round-trips through the canonical ABI correctly.
	#[tokio::test]
	async fn smoke_load_metadata_fixture() {
		let fixture = Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/metadata_fixture.wasm"));
		assert!(fixture.exists(), "fixture not found; re-run cargo build to regenerate");

		let rt = WasmtimeRuntime::new(mock_backend()).expect("runtime");
		let meta = rt.load_component(fixture).await.expect("load_component");

		assert_eq!(meta.name, "fixture");
		assert_eq!(meta.abi_version, "0.1.0");
		assert_eq!(meta.exports.len(), 1);
		assert_eq!(meta.exports[0].name, "probe");
		assert_eq!(meta.exports[0].kind, MiddlewareKind::L4Peek);
		assert!(meta.exports[0].stateless);
	}

	// load_component must reject a component whose metadata claims kind K but the
	// component binary does not export the corresponding handler interface.
	#[tokio::test]
	async fn load_component_rejects_missing_handler_interface() {
		let fixture = Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/mismatch_fixture.wasm"));
		assert!(fixture.exists(), "mismatch fixture not found; re-run cargo build to regenerate");

		let rt = WasmtimeRuntime::new(mock_backend()).expect("runtime");
		let err = rt.load_component(fixture).await.expect_err("must reject mismatch");
		let msg = err.to_string();
		assert!(
			msg.contains("handler") || msg.contains("l4-peek"),
			"error should mention the missing handler: {msg}",
		);
	}
}
