//! vane WASM plugin runtime: wasmtime + Component Model + instance pooling + host functions.
//!
//! See `spec/architecture/11-wasm.md`.

#![allow(unsafe_code)] // Component::deserialize_file is unsafe per wasmtime API

use std::collections::HashMap;
use std::path::Path;
use std::sync::{Arc, Mutex, RwLock, Weak};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use rand::Rng;
use sha2::{Digest, Sha256};
use tracing::{trace, warn};
use wasmtime::component::{Component, HasSelf, Linker};
use wasmtime::{Config, Engine, PoolingAllocationConfig, Store};

use vane_core::middleware::MiddlewareKind;
use vane_core::{
	BytesView, ContextEntry, ContextValue, Error, Header, HttpFetchBackend, HttpFetchError,
	HttpFetchLimits, HttpFetchRequest, L4BytesDecision, L4BytesInput, L4PeekDecision, L4PeekInput,
	L7RequestDecision, L7RequestInput, L7ResponseDecision, L7ResponseInput, ModifiedResponse,
	ModuleId, PluginError, PluginExport, PluginMetadata, SynthResponse, WasmPoolStats,
	WasmPoolSummary, WasmRuntime,
};

// Generate host-side bindings from the WIT world. This produces:
//   - `Plugin` struct (instantiated component accessor)
//   - `vane::host::host::Host` trait (host import implementations, RPITIT async)
//   - `Plugin::add_to_linker` for wiring host functions
wasmtime::component::bindgen!({
		path: "wit",
		world: "plugin",
		imports: {
				default: async | trappable,
		},
});

mod invoke_l4peek {
	wasmtime::component::bindgen!({
		path: "wit",
		world: "plugin-l4-peek-invoke",
		imports: {
			default: async | trappable,
		},
	});
}

mod invoke_l4bytes {
	wasmtime::component::bindgen!({
		path: "wit",
		world: "plugin-l4-bytes-invoke",
		imports: {
			default: async | trappable,
		},
	});
}

mod invoke_l7request {
	wasmtime::component::bindgen!({
		path: "wit",
		world: "plugin-l7-request-invoke",
		imports: {
			default: async | trappable,
		},
	});
}

mod invoke_l7response {
	wasmtime::component::bindgen!({
		path: "wit",
		world: "plugin-l7-response-invoke",
		imports: {
			default: async | trappable,
		},
	});
}

// ─── host state ──────────────────────────────────────────────────────────────

/// Per-Store state threaded through every host function call.
struct HostState {
	args: String,
	fetch_backend: Arc<dyn HttpFetchBackend>,
	/// Captures the last value returned by `get_args` during an invocation.
	/// Used by `StatefulPoolHandle::last_args_received` in tests to verify
	/// that the fixture plugin actually called host.get-args and received the
	/// bound args string.
	#[cfg(test)]
	args_received: Option<String>,
}

impl HostState {
	fn new(args: String, fetch_backend: Arc<dyn HttpFetchBackend>) -> Self {
		Self {
			args,
			fetch_backend,
			#[cfg(test)]
			args_received: None,
		}
	}
}

// vane:plugin/types has no functions; the generated Host trait is empty.
impl vane::plugin::types::Host for HostState {}

// Implement the host import trait generated by `bindgen!`.
// Native async fn is used (RPITIT, no #[async_trait]).
impl vane::host::host::Host for HostState {
	async fn get_args(&mut self) -> wasmtime::Result<String> {
		let result = self.args.clone();
		#[cfg(test)]
		{
			self.args_received = Some(result.clone());
		}
		Ok(result)
	}

	async fn log(
		&mut self,
		level: vane::host::host::LogLevel,
		message: String,
		fields: Vec<vane::host::host::LogField>,
	) -> wasmtime::Result<()> {
		use vane::host::host::LogLevel;
		let kv: String = fields.iter().fold(String::new(), |mut s, f| {
			use std::fmt::Write as _;
			let _ = write!(s, " {}={}", f.key, f.value);
			s
		});
		match level {
			LogLevel::Trace => trace!(plugin = true, "{message}{kv}"),
			LogLevel::Debug => tracing::debug!(plugin = true, "{message}{kv}"),
			LogLevel::Info => tracing::info!(plugin = true, "{message}{kv}"),
			LogLevel::Warn => warn!(plugin = true, "{message}{kv}"),
			LogLevel::Error => tracing::error!(plugin = true, "{message}{kv}"),
		}
		Ok(())
	}

	async fn now_unix_ms(&mut self) -> wasmtime::Result<u64> {
		let d = SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default();
		Ok(d.as_secs() * 1000 + u64::from(d.subsec_millis()))
	}

	async fn random(&mut self, buf_len: u32) -> wasmtime::Result<Vec<u8>> {
		let mut buf = vec![0u8; buf_len as usize];
		rand::rng().fill_bytes(&mut buf);
		Ok(buf)
	}

	async fn metric_counter(
		&mut self,
		_name: String,
		_delta: u64,
		_labels: Vec<vane::host::host::MetricLabel>,
	) -> wasmtime::Result<()> {
		// TODO(wasm-metrics): route to daemon metrics facade
		Ok(())
	}

	async fn metric_gauge(
		&mut self,
		_name: String,
		_value: i64,
		_labels: Vec<vane::host::host::MetricLabel>,
	) -> wasmtime::Result<()> {
		// TODO(wasm-metrics): route to daemon metrics facade
		Ok(())
	}

	async fn http_fetch(
		&mut self,
		req: vane::host::host::HttpFetchRequest,
	) -> wasmtime::Result<Result<vane::host::host::HttpFetchResponse, vane::host::host::NetError>> {
		let vane_req = HttpFetchRequest {
			method: req.method,
			url: req.url,
			headers: req.headers,
			body: req.body,
			timeout_ms: req.timeout_ms,
			follow_redirects: req.follow_redirects,
			verify_tls: req.verify_tls,
		};
		let limits = HttpFetchLimits::default();
		match self.fetch_backend.fetch(vane_req, limits).await {
			Ok(resp) => Ok(Ok(vane::host::host::HttpFetchResponse {
				status: resp.status,
				headers: resp.headers,
				body: resp.body,
			})),
			Err(e) => Ok(Err(map_fetch_error(e))),
		}
	}
}

// ─── invoke_l4peek host trait impls ──────────────────────────────────────────

impl invoke_l4peek::vane::plugin::types::Host for HostState {}

impl invoke_l4peek::vane::host::host::Host for HostState {
	async fn get_args(&mut self) -> wasmtime::Result<String> {
		let result = self.args.clone();
		#[cfg(test)]
		{
			self.args_received = Some(result.clone());
		}
		Ok(result)
	}

	async fn log(
		&mut self,
		level: invoke_l4peek::vane::host::host::LogLevel,
		message: String,
		fields: Vec<invoke_l4peek::vane::host::host::LogField>,
	) -> wasmtime::Result<()> {
		use invoke_l4peek::vane::host::host::LogLevel;
		let kv: String = fields.iter().fold(String::new(), |mut s, f| {
			use std::fmt::Write as _;
			let _ = write!(s, " {}={}", f.key, f.value);
			s
		});
		match level {
			LogLevel::Trace => trace!(plugin = true, "{message}{kv}"),
			LogLevel::Debug => tracing::debug!(plugin = true, "{message}{kv}"),
			LogLevel::Info => tracing::info!(plugin = true, "{message}{kv}"),
			LogLevel::Warn => warn!(plugin = true, "{message}{kv}"),
			LogLevel::Error => tracing::error!(plugin = true, "{message}{kv}"),
		}
		Ok(())
	}

	async fn now_unix_ms(&mut self) -> wasmtime::Result<u64> {
		let d = SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default();
		Ok(d.as_secs() * 1000 + u64::from(d.subsec_millis()))
	}

	async fn random(&mut self, buf_len: u32) -> wasmtime::Result<Vec<u8>> {
		let mut buf = vec![0u8; buf_len as usize];
		rand::rng().fill_bytes(&mut buf);
		Ok(buf)
	}

	async fn metric_counter(
		&mut self,
		_name: String,
		_delta: u64,
		_labels: Vec<invoke_l4peek::vane::host::host::MetricLabel>,
	) -> wasmtime::Result<()> {
		// TODO(wasm-metrics): route to daemon metrics facade
		Ok(())
	}

	async fn metric_gauge(
		&mut self,
		_name: String,
		_value: i64,
		_labels: Vec<invoke_l4peek::vane::host::host::MetricLabel>,
	) -> wasmtime::Result<()> {
		// TODO(wasm-metrics): route to daemon metrics facade
		Ok(())
	}

	async fn http_fetch(
		&mut self,
		req: invoke_l4peek::vane::host::host::HttpFetchRequest,
	) -> wasmtime::Result<
		Result<
			invoke_l4peek::vane::host::host::HttpFetchResponse,
			invoke_l4peek::vane::host::host::NetError,
		>,
	> {
		let vane_req = HttpFetchRequest {
			method: req.method,
			url: req.url,
			headers: req.headers,
			body: req.body,
			timeout_ms: req.timeout_ms,
			follow_redirects: req.follow_redirects,
			verify_tls: req.verify_tls,
		};
		let limits = HttpFetchLimits::default();
		match self.fetch_backend.fetch(vane_req, limits).await {
			Ok(resp) => Ok(Ok(invoke_l4peek::vane::host::host::HttpFetchResponse {
				status: resp.status,
				headers: resp.headers,
				body: resp.body,
			})),
			Err(e) => Ok(Err(map_fetch_error_invoke(e))),
		}
	}
}

// ─── host impls for invoke_l4bytes / invoke_l7request / invoke_l7response ───

impl invoke_l4bytes::vane::plugin::types::Host for HostState {}

impl invoke_l4bytes::vane::host::host::Host for HostState {
	async fn get_args(&mut self) -> wasmtime::Result<String> {
		let result = self.args.clone();
		#[cfg(test)]
		{
			self.args_received = Some(result.clone());
		}
		Ok(result)
	}

	async fn log(
		&mut self,
		level: invoke_l4bytes::vane::host::host::LogLevel,
		message: String,
		fields: Vec<invoke_l4bytes::vane::host::host::LogField>,
	) -> wasmtime::Result<()> {
		use invoke_l4bytes::vane::host::host::LogLevel;
		let kv: String = fields.iter().fold(String::new(), |mut s, f| {
			use std::fmt::Write as _;
			let _ = write!(s, " {}={}", f.key, f.value);
			s
		});
		match level {
			LogLevel::Trace => trace!(plugin = true, "{message}{kv}"),
			LogLevel::Debug => tracing::debug!(plugin = true, "{message}{kv}"),
			LogLevel::Info => tracing::info!(plugin = true, "{message}{kv}"),
			LogLevel::Warn => warn!(plugin = true, "{message}{kv}"),
			LogLevel::Error => tracing::error!(plugin = true, "{message}{kv}"),
		}
		Ok(())
	}

	async fn now_unix_ms(&mut self) -> wasmtime::Result<u64> {
		let d = std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap_or_default();
		Ok(d.as_secs() * 1000 + u64::from(d.subsec_millis()))
	}

	async fn random(&mut self, buf_len: u32) -> wasmtime::Result<Vec<u8>> {
		let mut buf = vec![0u8; buf_len as usize];
		rand::rng().fill_bytes(&mut buf);
		Ok(buf)
	}

	async fn metric_counter(
		&mut self,
		_name: String,
		_delta: u64,
		_labels: Vec<invoke_l4bytes::vane::host::host::MetricLabel>,
	) -> wasmtime::Result<()> {
		// TODO(wasm-metrics): route to daemon metrics facade
		Ok(())
	}

	async fn metric_gauge(
		&mut self,
		_name: String,
		_value: i64,
		_labels: Vec<invoke_l4bytes::vane::host::host::MetricLabel>,
	) -> wasmtime::Result<()> {
		// TODO(wasm-metrics): route to daemon metrics facade
		Ok(())
	}

	async fn http_fetch(
		&mut self,
		req: invoke_l4bytes::vane::host::host::HttpFetchRequest,
	) -> wasmtime::Result<
		Result<
			invoke_l4bytes::vane::host::host::HttpFetchResponse,
			invoke_l4bytes::vane::host::host::NetError,
		>,
	> {
		let vane_req = HttpFetchRequest {
			method: req.method,
			url: req.url,
			headers: req.headers,
			body: req.body,
			timeout_ms: req.timeout_ms,
			follow_redirects: req.follow_redirects,
			verify_tls: req.verify_tls,
		};
		let limits = HttpFetchLimits::default();
		match self.fetch_backend.fetch(vane_req, limits).await {
			Ok(resp) => Ok(Ok(invoke_l4bytes::vane::host::host::HttpFetchResponse {
				status: resp.status,
				headers: resp.headers,
				body: resp.body,
			})),
			Err(e) => Ok(Err(map_fetch_error_l4bytes(e))),
		}
	}
}

impl invoke_l7request::vane::plugin::types::Host for HostState {}

impl invoke_l7request::vane::host::host::Host for HostState {
	async fn get_args(&mut self) -> wasmtime::Result<String> {
		let result = self.args.clone();
		#[cfg(test)]
		{
			self.args_received = Some(result.clone());
		}
		Ok(result)
	}

	async fn log(
		&mut self,
		level: invoke_l7request::vane::host::host::LogLevel,
		message: String,
		fields: Vec<invoke_l7request::vane::host::host::LogField>,
	) -> wasmtime::Result<()> {
		use invoke_l7request::vane::host::host::LogLevel;
		let kv: String = fields.iter().fold(String::new(), |mut s, f| {
			use std::fmt::Write as _;
			let _ = write!(s, " {}={}", f.key, f.value);
			s
		});
		match level {
			LogLevel::Trace => trace!(plugin = true, "{message}{kv}"),
			LogLevel::Debug => tracing::debug!(plugin = true, "{message}{kv}"),
			LogLevel::Info => tracing::info!(plugin = true, "{message}{kv}"),
			LogLevel::Warn => warn!(plugin = true, "{message}{kv}"),
			LogLevel::Error => tracing::error!(plugin = true, "{message}{kv}"),
		}
		Ok(())
	}

	async fn now_unix_ms(&mut self) -> wasmtime::Result<u64> {
		let d = std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap_or_default();
		Ok(d.as_secs() * 1000 + u64::from(d.subsec_millis()))
	}

	async fn random(&mut self, buf_len: u32) -> wasmtime::Result<Vec<u8>> {
		let mut buf = vec![0u8; buf_len as usize];
		rand::rng().fill_bytes(&mut buf);
		Ok(buf)
	}

	async fn metric_counter(
		&mut self,
		_name: String,
		_delta: u64,
		_labels: Vec<invoke_l7request::vane::host::host::MetricLabel>,
	) -> wasmtime::Result<()> {
		// TODO(wasm-metrics): route to daemon metrics facade
		Ok(())
	}

	async fn metric_gauge(
		&mut self,
		_name: String,
		_value: i64,
		_labels: Vec<invoke_l7request::vane::host::host::MetricLabel>,
	) -> wasmtime::Result<()> {
		// TODO(wasm-metrics): route to daemon metrics facade
		Ok(())
	}

	async fn http_fetch(
		&mut self,
		req: invoke_l7request::vane::host::host::HttpFetchRequest,
	) -> wasmtime::Result<
		Result<
			invoke_l7request::vane::host::host::HttpFetchResponse,
			invoke_l7request::vane::host::host::NetError,
		>,
	> {
		let vane_req = HttpFetchRequest {
			method: req.method,
			url: req.url,
			headers: req.headers,
			body: req.body,
			timeout_ms: req.timeout_ms,
			follow_redirects: req.follow_redirects,
			verify_tls: req.verify_tls,
		};
		let limits = HttpFetchLimits::default();
		match self.fetch_backend.fetch(vane_req, limits).await {
			Ok(resp) => Ok(Ok(invoke_l7request::vane::host::host::HttpFetchResponse {
				status: resp.status,
				headers: resp.headers,
				body: resp.body,
			})),
			Err(e) => Ok(Err(map_fetch_error_l7request(e))),
		}
	}
}

impl invoke_l7response::vane::plugin::types::Host for HostState {}

impl invoke_l7response::vane::host::host::Host for HostState {
	async fn get_args(&mut self) -> wasmtime::Result<String> {
		let result = self.args.clone();
		#[cfg(test)]
		{
			self.args_received = Some(result.clone());
		}
		Ok(result)
	}

	async fn log(
		&mut self,
		level: invoke_l7response::vane::host::host::LogLevel,
		message: String,
		fields: Vec<invoke_l7response::vane::host::host::LogField>,
	) -> wasmtime::Result<()> {
		use invoke_l7response::vane::host::host::LogLevel;
		let kv: String = fields.iter().fold(String::new(), |mut s, f| {
			use std::fmt::Write as _;
			let _ = write!(s, " {}={}", f.key, f.value);
			s
		});
		match level {
			LogLevel::Trace => trace!(plugin = true, "{message}{kv}"),
			LogLevel::Debug => tracing::debug!(plugin = true, "{message}{kv}"),
			LogLevel::Info => tracing::info!(plugin = true, "{message}{kv}"),
			LogLevel::Warn => warn!(plugin = true, "{message}{kv}"),
			LogLevel::Error => tracing::error!(plugin = true, "{message}{kv}"),
		}
		Ok(())
	}

	async fn now_unix_ms(&mut self) -> wasmtime::Result<u64> {
		let d = std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap_or_default();
		Ok(d.as_secs() * 1000 + u64::from(d.subsec_millis()))
	}

	async fn random(&mut self, buf_len: u32) -> wasmtime::Result<Vec<u8>> {
		let mut buf = vec![0u8; buf_len as usize];
		rand::rng().fill_bytes(&mut buf);
		Ok(buf)
	}

	async fn metric_counter(
		&mut self,
		_name: String,
		_delta: u64,
		_labels: Vec<invoke_l7response::vane::host::host::MetricLabel>,
	) -> wasmtime::Result<()> {
		// TODO(wasm-metrics): route to daemon metrics facade
		Ok(())
	}

	async fn metric_gauge(
		&mut self,
		_name: String,
		_value: i64,
		_labels: Vec<invoke_l7response::vane::host::host::MetricLabel>,
	) -> wasmtime::Result<()> {
		// TODO(wasm-metrics): route to daemon metrics facade
		Ok(())
	}

	async fn http_fetch(
		&mut self,
		req: invoke_l7response::vane::host::host::HttpFetchRequest,
	) -> wasmtime::Result<
		Result<
			invoke_l7response::vane::host::host::HttpFetchResponse,
			invoke_l7response::vane::host::host::NetError,
		>,
	> {
		let vane_req = HttpFetchRequest {
			method: req.method,
			url: req.url,
			headers: req.headers,
			body: req.body,
			timeout_ms: req.timeout_ms,
			follow_redirects: req.follow_redirects,
			verify_tls: req.verify_tls,
		};
		let limits = HttpFetchLimits::default();
		match self.fetch_backend.fetch(vane_req, limits).await {
			Ok(resp) => Ok(Ok(invoke_l7response::vane::host::host::HttpFetchResponse {
				status: resp.status,
				headers: resp.headers,
				body: resp.body,
			})),
			Err(e) => Ok(Err(map_fetch_error_l7response(e))),
		}
	}
}

fn map_fetch_error(e: HttpFetchError) -> vane::host::host::NetError {
	use vane::host::host::NetError;
	match e {
		HttpFetchError::DnsFailure(s) => NetError::DnsFailure(s),
		HttpFetchError::ConnectionRefused => NetError::ConnectionRefused,
		HttpFetchError::Timeout => NetError::Timeout,
		HttpFetchError::TlsError(s) => NetError::TlsError(s),
		HttpFetchError::PoolExhausted => NetError::PoolExhausted,
		HttpFetchError::BodyTooLarge => NetError::BodyTooLarge,
		HttpFetchError::NotAllowed(s) => NetError::NotAllowed(s),
		HttpFetchError::InsecureRejected => NetError::InsecureRejected,
		HttpFetchError::Internal(s) => NetError::Internal(s),
	}
}

fn map_fetch_error_invoke(e: HttpFetchError) -> invoke_l4peek::vane::host::host::NetError {
	use invoke_l4peek::vane::host::host::NetError;
	match e {
		HttpFetchError::DnsFailure(s) => NetError::DnsFailure(s),
		HttpFetchError::ConnectionRefused => NetError::ConnectionRefused,
		HttpFetchError::Timeout => NetError::Timeout,
		HttpFetchError::TlsError(s) => NetError::TlsError(s),
		HttpFetchError::PoolExhausted => NetError::PoolExhausted,
		HttpFetchError::BodyTooLarge => NetError::BodyTooLarge,
		HttpFetchError::NotAllowed(s) => NetError::NotAllowed(s),
		HttpFetchError::InsecureRejected => NetError::InsecureRejected,
		HttpFetchError::Internal(s) => NetError::Internal(s),
	}
}

fn map_fetch_error_l4bytes(e: HttpFetchError) -> invoke_l4bytes::vane::host::host::NetError {
	use invoke_l4bytes::vane::host::host::NetError;
	match e {
		HttpFetchError::DnsFailure(s) => NetError::DnsFailure(s),
		HttpFetchError::ConnectionRefused => NetError::ConnectionRefused,
		HttpFetchError::Timeout => NetError::Timeout,
		HttpFetchError::TlsError(s) => NetError::TlsError(s),
		HttpFetchError::PoolExhausted => NetError::PoolExhausted,
		HttpFetchError::BodyTooLarge => NetError::BodyTooLarge,
		HttpFetchError::NotAllowed(s) => NetError::NotAllowed(s),
		HttpFetchError::InsecureRejected => NetError::InsecureRejected,
		HttpFetchError::Internal(s) => NetError::Internal(s),
	}
}

fn map_fetch_error_l7request(e: HttpFetchError) -> invoke_l7request::vane::host::host::NetError {
	use invoke_l7request::vane::host::host::NetError;
	match e {
		HttpFetchError::DnsFailure(s) => NetError::DnsFailure(s),
		HttpFetchError::ConnectionRefused => NetError::ConnectionRefused,
		HttpFetchError::Timeout => NetError::Timeout,
		HttpFetchError::TlsError(s) => NetError::TlsError(s),
		HttpFetchError::PoolExhausted => NetError::PoolExhausted,
		HttpFetchError::BodyTooLarge => NetError::BodyTooLarge,
		HttpFetchError::NotAllowed(s) => NetError::NotAllowed(s),
		HttpFetchError::InsecureRejected => NetError::InsecureRejected,
		HttpFetchError::Internal(s) => NetError::Internal(s),
	}
}

fn map_fetch_error_l7response(e: HttpFetchError) -> invoke_l7response::vane::host::host::NetError {
	use invoke_l7response::vane::host::host::NetError;
	match e {
		HttpFetchError::DnsFailure(s) => NetError::DnsFailure(s),
		HttpFetchError::ConnectionRefused => NetError::ConnectionRefused,
		HttpFetchError::Timeout => NetError::Timeout,
		HttpFetchError::TlsError(s) => NetError::TlsError(s),
		HttpFetchError::PoolExhausted => NetError::PoolExhausted,
		HttpFetchError::BodyTooLarge => NetError::BodyTooLarge,
		HttpFetchError::NotAllowed(s) => NetError::NotAllowed(s),
		HttpFetchError::InsecureRejected => NetError::InsecureRejected,
		HttpFetchError::Internal(s) => NetError::Internal(s),
	}
}

// ─── type translation helpers ────────────────────────────────────────────────

fn lower_context_value(v: ContextValue) -> invoke_l4peek::vane::plugin::types::ContextValue {
	use invoke_l4peek::vane::plugin::types::ContextValue as WitCV;
	match v {
		ContextValue::Text(s) => WitCV::Text(s),
		ContextValue::Bytes(b) => WitCV::Bytes(b),
		ContextValue::Int64(i) => WitCV::Int64(i),
		ContextValue::Uint64(u) => WitCV::Uint64(u),
		ContextValue::Boolean(b) => WitCV::Boolean(b),
		ContextValue::ListText(l) => WitCV::ListText(l),
	}
}

fn lower_context_entry(e: ContextEntry) -> invoke_l4peek::vane::plugin::types::ContextEntry {
	invoke_l4peek::vane::plugin::types::ContextEntry {
		path: e.path,
		value: lower_context_value(e.value),
	}
}

fn lower_input(
	input: L4PeekInput,
) -> invoke_l4peek::exports::vane::plugin::handler_l4_peek::L4PeekInput {
	invoke_l4peek::exports::vane::plugin::handler_l4_peek::L4PeekInput {
		peek: input.peek,
		context: input.context.into_iter().map(lower_context_entry).collect(),
	}
}

fn lift_decision(
	d: invoke_l4peek::exports::vane::plugin::handler_l4_peek::L4PeekDecision,
) -> L4PeekDecision {
	use invoke_l4peek::exports::vane::plugin::handler_l4_peek::L4PeekDecision as WitD;
	match d {
		WitD::Continue => L4PeekDecision::Continue,
		WitD::Close => L4PeekDecision::Close,
	}
}

fn lift_plugin_error(pe: invoke_l4peek::vane::plugin::types::PluginError) -> PluginError {
	PluginError::Plugin { code: pe.code, message: pe.message, on_error_hint: pe.on_error_hint }
}

// ─── validation ──────────────────────────────────────────────────────────────

fn validate_on_error_hint(hint: Option<&String>) -> Result<(), PluginError> {
	match hint.map(String::as_str) {
		None | Some("force-close" | "internal") => Ok(()),
		Some(v) => Err(PluginError::Trap(format!("invalid on-error-hint value: '{v}'"))),
	}
}

fn validate_status(status: u16) -> Result<(), PluginError> {
	if (100..=599).contains(&status) {
		Ok(())
	} else {
		Err(PluginError::Trap(format!("plugin returned invalid HTTP status {status}")))
	}
}

fn validate_header_name(name: &str) -> Result<(), PluginError> {
	if name.bytes().any(|b| matches!(b, b'\r' | b'\n' | 0)) {
		Err(PluginError::Trap(format!("header name contains CR, LF, or NUL: {name:?}")))
	} else {
		Ok(())
	}
}

fn validate_header_value(value: &str) -> Result<(), PluginError> {
	if value.bytes().any(|b| matches!(b, b'\r' | b'\n' | 0)) {
		Err(PluginError::Trap("header value contains CR, LF, or NUL".into()))
	} else {
		Ok(())
	}
}

// ─── type translation helpers (invoke_l4bytes) ───────────────────────────────

fn lower_context_value_l4bytes(
	v: ContextValue,
) -> invoke_l4bytes::vane::plugin::types::ContextValue {
	use invoke_l4bytes::vane::plugin::types::ContextValue as WitCV;
	match v {
		ContextValue::Text(s) => WitCV::Text(s),
		ContextValue::Bytes(b) => WitCV::Bytes(b),
		ContextValue::Int64(i) => WitCV::Int64(i),
		ContextValue::Uint64(u) => WitCV::Uint64(u),
		ContextValue::Boolean(b) => WitCV::Boolean(b),
		ContextValue::ListText(l) => WitCV::ListText(l),
	}
}

fn lower_context_entry_l4bytes(
	e: ContextEntry,
) -> invoke_l4bytes::vane::plugin::types::ContextEntry {
	invoke_l4bytes::vane::plugin::types::ContextEntry {
		path: e.path,
		value: lower_context_value_l4bytes(e.value),
	}
}

fn lower_bytes_view_l4bytes(bv: BytesView) -> invoke_l4bytes::vane::plugin::types::BytesView {
	invoke_l4bytes::vane::plugin::types::BytesView { data: bv.data, truncated: bv.truncated }
}

fn lower_l4bytes_input(
	input: L4BytesInput,
) -> invoke_l4bytes::exports::vane::plugin::handler_l4_bytes::L4BytesInput {
	invoke_l4bytes::exports::vane::plugin::handler_l4_bytes::L4BytesInput {
		bytes: lower_bytes_view_l4bytes(input.bytes),
		context: input.context.into_iter().map(lower_context_entry_l4bytes).collect(),
	}
}

fn lift_l4bytes_decision(
	d: invoke_l4bytes::exports::vane::plugin::handler_l4_bytes::L4BytesDecision,
) -> L4BytesDecision {
	use invoke_l4bytes::exports::vane::plugin::handler_l4_bytes::L4BytesDecision as WitD;
	match d {
		WitD::Continue => L4BytesDecision::Continue,
		WitD::Tunnel => L4BytesDecision::Tunnel,
		WitD::Close => L4BytesDecision::Close,
	}
}

fn lift_plugin_error_l4bytes(
	pe: invoke_l4bytes::vane::plugin::types::PluginError,
) -> Result<PluginError, PluginError> {
	validate_on_error_hint(pe.on_error_hint.as_ref())?;
	Ok(PluginError::Plugin { code: pe.code, message: pe.message, on_error_hint: pe.on_error_hint })
}

// ─── type translation helpers (invoke_l7request) ─────────────────────────────

fn lower_context_value_l7request(
	v: ContextValue,
) -> invoke_l7request::vane::plugin::types::ContextValue {
	use invoke_l7request::vane::plugin::types::ContextValue as WitCV;
	match v {
		ContextValue::Text(s) => WitCV::Text(s),
		ContextValue::Bytes(b) => WitCV::Bytes(b),
		ContextValue::Int64(i) => WitCV::Int64(i),
		ContextValue::Uint64(u) => WitCV::Uint64(u),
		ContextValue::Boolean(b) => WitCV::Boolean(b),
		ContextValue::ListText(l) => WitCV::ListText(l),
	}
}

fn lower_context_entry_l7request(
	e: ContextEntry,
) -> invoke_l7request::vane::plugin::types::ContextEntry {
	invoke_l7request::vane::plugin::types::ContextEntry {
		path: e.path,
		value: lower_context_value_l7request(e.value),
	}
}

fn lower_bytes_view_l7request(bv: BytesView) -> invoke_l7request::vane::plugin::types::BytesView {
	invoke_l7request::vane::plugin::types::BytesView { data: bv.data, truncated: bv.truncated }
}

fn lower_header_l7request(h: Header) -> invoke_l7request::vane::plugin::types::Header {
	invoke_l7request::vane::plugin::types::Header {
		name: h.name.to_ascii_lowercase(),
		value: h.value,
	}
}

fn lower_l7request_input(
	input: L7RequestInput,
) -> invoke_l7request::exports::vane::plugin::handler_l7_request::L7RequestInput {
	invoke_l7request::exports::vane::plugin::handler_l7_request::L7RequestInput {
		method: input.method,
		uri: input.uri,
		headers: input.headers.into_iter().map(lower_header_l7request).collect(),
		body: input.body.map(lower_bytes_view_l7request),
		context: input.context.into_iter().map(lower_context_entry_l7request).collect(),
	}
}

fn lift_l7request_decision(
	d: invoke_l7request::exports::vane::plugin::handler_l7_request::L7RequestDecision,
) -> Result<L7RequestDecision, PluginError> {
	use invoke_l7request::exports::vane::plugin::handler_l7_request::L7RequestDecision as WitD;
	match d {
		WitD::Continue => Ok(L7RequestDecision::Continue),
		WitD::Close => Ok(L7RequestDecision::Close),
		WitD::Short(sr) => {
			validate_status(sr.status)?;
			for h in &sr.headers {
				validate_header_name(&h.name)?;
				validate_header_value(&h.value)?;
			}
			let headers =
				sr.headers.into_iter().map(|h| Header { name: h.name, value: h.value }).collect();
			Ok(L7RequestDecision::Short(SynthResponse { status: sr.status, headers, body: sr.body }))
		}
	}
}

fn lift_plugin_error_l7request(
	pe: invoke_l7request::vane::plugin::types::PluginError,
) -> Result<PluginError, PluginError> {
	validate_on_error_hint(pe.on_error_hint.as_ref())?;
	Ok(PluginError::Plugin { code: pe.code, message: pe.message, on_error_hint: pe.on_error_hint })
}

// ─── type translation helpers (invoke_l7response) ────────────────────────────

fn lower_context_value_l7response(
	v: ContextValue,
) -> invoke_l7response::vane::plugin::types::ContextValue {
	use invoke_l7response::vane::plugin::types::ContextValue as WitCV;
	match v {
		ContextValue::Text(s) => WitCV::Text(s),
		ContextValue::Bytes(b) => WitCV::Bytes(b),
		ContextValue::Int64(i) => WitCV::Int64(i),
		ContextValue::Uint64(u) => WitCV::Uint64(u),
		ContextValue::Boolean(b) => WitCV::Boolean(b),
		ContextValue::ListText(l) => WitCV::ListText(l),
	}
}

fn lower_context_entry_l7response(
	e: ContextEntry,
) -> invoke_l7response::vane::plugin::types::ContextEntry {
	invoke_l7response::vane::plugin::types::ContextEntry {
		path: e.path,
		value: lower_context_value_l7response(e.value),
	}
}

fn lower_bytes_view_l7response(bv: BytesView) -> invoke_l7response::vane::plugin::types::BytesView {
	invoke_l7response::vane::plugin::types::BytesView { data: bv.data, truncated: bv.truncated }
}

fn lower_header_l7response(h: Header) -> invoke_l7response::vane::plugin::types::Header {
	invoke_l7response::vane::plugin::types::Header {
		name: h.name.to_ascii_lowercase(),
		value: h.value,
	}
}

fn lower_l7response_input(
	input: L7ResponseInput,
) -> invoke_l7response::exports::vane::plugin::handler_l7_response::L7ResponseInput {
	invoke_l7response::exports::vane::plugin::handler_l7_response::L7ResponseInput {
		status: input.status,
		headers: input.headers.into_iter().map(lower_header_l7response).collect(),
		body: input.body.map(lower_bytes_view_l7response),
		context: input.context.into_iter().map(lower_context_entry_l7response).collect(),
	}
}

fn lift_l7response_decision(
	d: invoke_l7response::exports::vane::plugin::handler_l7_response::L7ResponseDecision,
) -> Result<L7ResponseDecision, PluginError> {
	use invoke_l7response::exports::vane::plugin::handler_l7_response::L7ResponseDecision as WitD;
	match d {
		WitD::Continue => Ok(L7ResponseDecision::Continue),
		WitD::Abort => Ok(L7ResponseDecision::Abort),
		WitD::Modify(mr) => {
			if let Some(status) = mr.status {
				validate_status(status)?;
			}
			if let Some(ref headers) = mr.headers {
				for h in headers {
					validate_header_name(&h.name)?;
					validate_header_value(&h.value)?;
				}
			}
			let headers = mr
				.headers
				.map(|hs| hs.into_iter().map(|h| Header { name: h.name, value: h.value }).collect());
			Ok(L7ResponseDecision::Modify(ModifiedResponse { status: mr.status, headers, body: mr.body }))
		}
	}
}

fn lift_plugin_error_l7response(
	pe: invoke_l7response::vane::plugin::types::PluginError,
) -> Result<PluginError, PluginError> {
	validate_on_error_hint(pe.on_error_hint.as_ref())?;
	Ok(PluginError::Plugin { code: pe.code, message: pe.message, on_error_hint: pe.on_error_hint })
}

// ─── WasmtimeRuntime ─────────────────────────────────────────────────────────

/// Expected ABI major version. Components whose `abi-version` has a different
/// major component are rejected at load time.
const ABI_MAJOR: u64 = 0;

/// Path to the compiled component cache.
const CWASM_CACHE_DIR: &str = "/var/lib/vaned/wasm";

/// Key for the stateless pool map: uniquely identifies a (module, export, args) triple.
#[derive(Clone, Hash, Eq, PartialEq)]
struct StatelessKey {
	module_id: String,
	export_name: String,
	args_json: String,
}

/// Pool metadata for a stateless export. Each rental instantiates a fresh store.
struct StatelessPool {
	component: Arc<Component>,
	#[allow(dead_code)]
	args_json: String,
	construction_count: Arc<std::sync::atomic::AtomicU64>,
}

/// A pre-allocated pool of warm stateful WASM instances for a single export.
///
/// Instances are checked out (popped), used, and returned (pushed). If the
/// pool is empty, `invoke_l4_peek` returns `PluginError::Exhausted` immediately
/// without blocking.
pub struct StatefulPoolHandle {
	// Stored for future dynamic pool growth and diagnostics.
	#[allow(dead_code)]
	component: Arc<Component>,
	#[allow(dead_code)]
	engine: Engine,
	#[allow(dead_code)]
	fetch_backend: Arc<dyn HttpFetchBackend>,
	#[allow(dead_code)]
	pub args_json: String,
	instances: Mutex<Vec<StatefulInstance>>,
	#[allow(dead_code)]
	pub capacity: usize,
	/// Identity used by `WasmtimeRuntime::pool_snapshot` to label this
	/// pool in mgmt verb output. Stored on the handle (rather than as
	/// a side map keyed off `Arc::as_ptr`) so the snapshot can echo
	/// the operator's module + export without a second registry.
	pub module_id: String,
	pub export_name: String,
}

struct StatefulInstance {
	store: Store<HostState>,
	plugin: invoke_l4peek::PluginL4PeekInvoke,
}

impl StatefulPoolHandle {
	/// Invoke the l4-peek handler using a pooled stateful instance.
	///
	/// Checkout is non-blocking: if no instance is available, returns
	/// `PluginError::Exhausted` immediately.
	///
	/// # Errors
	///
	/// Returns `PluginError::Exhausted` if no instance is available.
	/// Returns `PluginError::Trap` if the guest traps or the epoch deadline fires.
	/// Returns `PluginError::Plugin` if the guest returns an in-band error.
	///
	/// # Panics
	///
	/// Panics if the internal instance mutex is poisoned.
	#[allow(clippy::unused_async)] // async required for consistent call-site ergonomics
	pub async fn invoke_l4_peek(
		&self,
		export_name: &str,
		input: L4PeekInput,
	) -> Result<L4PeekDecision, PluginError> {
		let mut instance = {
			let mut guard = self.instances.lock().unwrap();
			guard.pop().ok_or(PluginError::Exhausted)?
		};

		instance.store.set_epoch_deadline(10);
		let wit_input = lower_input(input);
		let result = instance.plugin.vane_plugin_handler_l4_peek().call_handle(
			&mut instance.store,
			export_name,
			&wit_input,
		);

		let outcome = match result {
			Ok(Ok(d)) => Ok(lift_decision(d)),
			Ok(Err(pe)) => Err(lift_plugin_error(pe)),
			Err(e) => Err(PluginError::Trap(e.to_string())),
		};

		{
			let mut guard = self.instances.lock().unwrap();
			guard.push(instance);
		}

		outcome
	}

	/// Returns the args string that the plugin received via `host.get-args` on
	/// the most recently returned instance, or `None` if `get-args` was never
	/// called during that invocation.
	///
	/// Only available in test builds; intended for use in
	/// `host_get_args_returns_bound_args_to_plugin` and similar.
	///
	/// # Panics
	///
	/// Panics if the instances mutex is poisoned.
	#[cfg(test)]
	pub fn last_args_received(&self) -> Option<String> {
		self.instances.lock().unwrap().last().and_then(|i| i.store.data().args_received.clone())
	}
}

pub struct WasmtimeRuntime {
	engine: Engine,
	fetch_backend: Arc<dyn HttpFetchBackend>,
	epoch_abort: tokio::task::AbortHandle,
	invoke_linker: Linker<HostState>,
	invoke_l4bytes_linker: Linker<HostState>,
	invoke_l7request_linker: Linker<HostState>,
	invoke_l7response_linker: Linker<HostState>,
	components: RwLock<HashMap<String, Arc<Component>>>,
	metadata: RwLock<HashMap<String, Arc<PluginMetadata>>>,
	stateless_pools: RwLock<HashMap<StatelessKey, Arc<StatelessPool>>>,
	/// Weak-ref registry of every live stateful pool returned by
	/// [`WasmtimeRuntime::create_stateful_pool`]. Holding `Weak` keeps
	/// the runtime out of the pool-handle ownership graph: when a flow
	/// graph reload drops the last `Arc`, the weak entry naturally
	/// invalidates and the next snapshot prunes it.
	stateful_pools: RwLock<Vec<Weak<StatefulPoolHandle>>>,
}

impl Drop for WasmtimeRuntime {
	fn drop(&mut self) {
		self.epoch_abort.abort();
	}
}

impl WasmtimeRuntime {
	/// Construct a new runtime. Starts the 1 ms epoch ticker immediately.
	///
	/// # Errors
	///
	/// Fails if wasmtime cannot build the pooling engine (unsupported platform
	/// or configuration conflict).
	pub fn new(fetch_backend: Arc<dyn HttpFetchBackend>) -> Result<Arc<Self>, Error> {
		Self::new_with_pool_cap(fetch_backend, 32)
	}

	/// Construct a runtime with a custom `PoolingAllocator` cap.
	///
	/// Useful in tests to exercise pool-exhaustion paths with a small cap.
	///
	/// # Errors
	///
	/// Fails if wasmtime cannot build the pooling engine (unsupported platform
	/// or configuration conflict).
	pub fn new_with_pool_cap(
		fetch_backend: Arc<dyn HttpFetchBackend>,
		pool_cap: u32,
	) -> Result<Arc<Self>, Error> {
		let engine = build_engine(pool_cap).map_err(|e| Error::internal(e.to_string()))?;

		let ticker_engine = engine.clone();
		let handle = tokio::spawn(async move {
			let mut interval = tokio::time::interval(Duration::from_millis(1));
			interval.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);
			loop {
				interval.tick().await;
				ticker_engine.increment_epoch();
			}
		});
		let epoch_abort = handle.abort_handle();

		let mut invoke_linker = Linker::<HostState>::new(&engine);
		invoke_l4peek::PluginL4PeekInvoke::add_to_linker::<HostState, HasSelf<HostState>>(
			&mut invoke_linker,
			|x| x,
		)
		.map_err(|e| Error::internal(format!("invoke linker setup: {e}")))?;

		let mut invoke_l4bytes_linker = Linker::<HostState>::new(&engine);
		invoke_l4bytes::PluginL4BytesInvoke::add_to_linker::<HostState, HasSelf<HostState>>(
			&mut invoke_l4bytes_linker,
			|x| x,
		)
		.map_err(|e| Error::internal(format!("l4bytes linker setup: {e}")))?;

		let mut invoke_l7request_linker = Linker::<HostState>::new(&engine);
		invoke_l7request::PluginL7RequestInvoke::add_to_linker::<HostState, HasSelf<HostState>>(
			&mut invoke_l7request_linker,
			|x| x,
		)
		.map_err(|e| Error::internal(format!("l7request linker setup: {e}")))?;

		let mut invoke_l7response_linker = Linker::<HostState>::new(&engine);
		invoke_l7response::PluginL7ResponseInvoke::add_to_linker::<HostState, HasSelf<HostState>>(
			&mut invoke_l7response_linker,
			|x| x,
		)
		.map_err(|e| Error::internal(format!("l7response linker setup: {e}")))?;

		Ok(Arc::new(Self {
			engine,
			fetch_backend,
			epoch_abort,
			invoke_linker,
			invoke_l4bytes_linker,
			invoke_l7request_linker,
			invoke_l7response_linker,
			components: RwLock::new(HashMap::new()),
			metadata: RwLock::new(HashMap::new()),
			stateless_pools: RwLock::new(HashMap::new()),
			stateful_pools: RwLock::new(Vec::new()),
		}))
	}

	/// Pre-allocate a fixed-size pool of warm stateful instances for the named export.
	///
	/// `pool_size` is clamped to `[1, 64]`. Each instance is fully instantiated
	/// at creation time; subsequent invocations only need a store epoch reset and
	/// a function call.
	///
	/// # Errors
	///
	/// Returns an error if the module has not been loaded, or if instantiation fails.
	///
	/// # Panics
	///
	/// Panics if the internal component or metadata `RwLock` is poisoned.
	pub async fn create_stateful_pool(
		&self,
		module_id: &ModuleId,
		export_name: &str,
		args_json: &str,
		pool_size: u8,
	) -> Result<Arc<StatefulPoolHandle>, Error> {
		let pool_size = (pool_size.clamp(1, 64)) as usize;
		let key = module_id.0.as_ref().to_owned();

		let component = self
			.components
			.read()
			.unwrap()
			.get(&key)
			.cloned()
			.ok_or_else(|| Error::internal("module not loaded"))?;

		let mut linker = Linker::<HostState>::new(&self.engine);
		invoke_l4peek::PluginL4PeekInvoke::add_to_linker::<HostState, HasSelf<HostState>>(
			&mut linker,
			|x| x,
		)
		.map_err(|e| Error::internal(format!("stateful linker setup: {e}")))?;

		let mut instances = Vec::with_capacity(pool_size);
		for _ in 0..pool_size {
			let host_state = HostState::new(args_json.to_owned(), Arc::clone(&self.fetch_backend));
			let mut store = Store::new(&self.engine, host_state);
			store.set_epoch_deadline(1000);
			let plugin =
				invoke_l4peek::PluginL4PeekInvoke::instantiate_async(&mut store, &component, &linker)
					.await
					.map_err(|e| Error::internal(format!("stateful instantiate: {e}")))?;
			instances.push(StatefulInstance { store, plugin });
		}

		let handle = Arc::new(StatefulPoolHandle {
			component,
			engine: self.engine.clone(),
			fetch_backend: Arc::clone(&self.fetch_backend),
			args_json: args_json.to_owned(),
			instances: Mutex::new(instances),
			capacity: pool_size,
			module_id: key,
			export_name: export_name.to_owned(),
		});
		// Register a weak ref so `pool_snapshot` can list this pool
		// without inflating its lifetime. Stale entries are pruned in
		// `pool_snapshot` itself.
		{
			let mut registry = self.stateful_pools.write().unwrap();
			registry.push(Arc::downgrade(&handle));
		}
		Ok(handle)
	}

	/// Read-only snapshot of every pool the runtime tracks: stateful
	/// pools (registered at creation time) and stateless pools (lazy,
	/// keyed by `(module, export, args_json)`). Surfaced via the
	/// `get_pools` mgmt verb.
	///
	/// Stateless pools have no pre-warmed capacity in MVP — each
	/// invocation instantiates a fresh store on demand. The snapshot
	/// reports `capacity = 0` and `available = 0` for those entries
	/// so the wire shape stays consistent with stateful pools; richer
	/// per-stateless counters (allocation totals, failures) land with
	/// the spec-mandated counters tracked by `pool-counters`.
	///
	/// # Panics
	///
	/// Panics if the internal `stateless_pools` or `stateful_pools`
	/// `RwLock` is poisoned.
	#[must_use]
	pub fn pool_snapshot(&self) -> Vec<WasmPoolSnapshot> {
		let mut out = Vec::new();
		// Stateful pools first: prune dead weak refs while we walk.
		let live: Vec<Arc<StatefulPoolHandle>> = {
			let mut registry = self.stateful_pools.write().unwrap();
			registry.retain(|w| w.strong_count() > 0);
			registry.iter().filter_map(Weak::upgrade).collect()
		};
		for pool in live {
			let available = pool.instances.lock().unwrap().len();
			out.push(WasmPoolSnapshot {
				kind: "stateful",
				key: pool.module_id.clone(),
				export: pool.export_name.clone(),
				capacity: pool.capacity,
				available,
			});
		}
		// Stateless pools: capacity / available are zero by design
		// (on-demand instantiation, no warm cache).
		let stateless = self.stateless_pools.read().unwrap();
		for (k, _pool) in stateless.iter() {
			out.push(WasmPoolSnapshot {
				kind: "stateless",
				key: k.module_id.clone(),
				export: k.export_name.clone(),
				capacity: 0,
				available: 0,
			});
		}
		out
	}
}

/// One entry in [`WasmtimeRuntime::pool_snapshot`]. Mirrors the wire
/// shape exposed by the `get_pools` mgmt verb, but lives in this crate
/// so `vane-mgmt` does not have to depend on `vane-wasm` to consume
/// the data — the daemon translates to the wire shape via the
/// [`WasmPoolStats`] trait.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WasmPoolSnapshot {
	pub kind: &'static str,
	pub key: String,
	pub export: String,
	pub capacity: usize,
	pub available: usize,
}

impl WasmPoolStats for WasmtimeRuntime {
	fn snapshot(&self) -> Vec<WasmPoolSummary> {
		self
			.pool_snapshot()
			.into_iter()
			.map(|s| WasmPoolSummary {
				kind: s.kind.to_owned(),
				key: s.key,
				export: s.export,
				capacity: s.capacity,
				available: s.available,
			})
			.collect()
	}
}

#[async_trait::async_trait]
impl WasmRuntime for WasmtimeRuntime {
	async fn load_component(&self, path: &Path) -> Result<Arc<PluginMetadata>, Error> {
		let bytes =
			std::fs::read(path).map_err(|e| Error::internal(format!("read {}: {e}", path.display())))?;

		let hash = hex_sha256(&bytes);
		let cwasm_path = std::path::PathBuf::from(CWASM_CACHE_DIR).join(format!("{hash}.cwasm"));

		let component = load_or_compile(&self.engine, path, &cwasm_path, &bytes)?;
		let meta = get_metadata(&self.engine, &component, Arc::clone(&self.fetch_backend)).await?;
		validate_handler_exports(&self.engine, &component, &meta.exports)?;

		let key = path.to_string_lossy().into_owned();
		self.components.write().unwrap().insert(key.clone(), Arc::new(component));
		self.metadata.write().unwrap().insert(key, Arc::clone(&meta));

		Ok(meta)
	}

	async fn invoke_l4_peek(
		&self,
		module_id: &ModuleId,
		export_name: &str,
		args_json: &str,
		input: L4PeekInput,
	) -> Result<L4PeekDecision, PluginError> {
		let key = module_id.0.as_ref().to_owned();

		let Some(component) = self.components.read().unwrap().get(&key).cloned() else {
			return Err(PluginError::Trap("module not loaded".into()));
		};

		let Some(meta) = self.metadata.read().unwrap().get(&key).cloned() else {
			return Err(PluginError::Trap("module not loaded".into()));
		};

		let Some(export_meta) = meta.exports.iter().find(|e| e.name == export_name) else {
			return Err(PluginError::Trap(format!("export '{export_name}' not found")));
		};

		if !export_meta.stateless {
			return Err(PluginError::Trap("stateful exports require StatefulPoolHandle".into()));
		}

		let skey = StatelessKey {
			module_id: key.clone(),
			export_name: export_name.to_owned(),
			args_json: args_json.to_owned(),
		};

		let pool = {
			let pools = self.stateless_pools.read().unwrap();
			pools.get(&skey).cloned()
		};

		let pool = if let Some(p) = pool {
			p
		} else {
			let new_pool = Arc::new(StatelessPool {
				component: Arc::clone(&component),
				args_json: args_json.to_owned(),
				construction_count: Arc::new(std::sync::atomic::AtomicU64::new(0)),
			});
			let mut pools = self.stateless_pools.write().unwrap();
			pools.entry(skey).or_insert(Arc::clone(&new_pool)).clone()
		};

		pool.construction_count.fetch_add(1, std::sync::atomic::Ordering::Relaxed);

		let host_state = HostState::new(args_json.to_owned(), Arc::clone(&self.fetch_backend));
		let mut store = Store::new(&self.engine, host_state);
		store.set_epoch_deadline(10);

		let plugin = match invoke_l4peek::PluginL4PeekInvoke::instantiate_async(
			&mut store,
			&pool.component,
			&self.invoke_linker,
		)
		.await
		{
			Ok(p) => p,
			Err(e) => return Err(PluginError::Trap(e.to_string())),
		};

		let wit_input = lower_input(input);
		let result =
			plugin.vane_plugin_handler_l4_peek().call_handle(&mut store, export_name, &wit_input);

		match result {
			Ok(Ok(d)) => Ok(lift_decision(d)),
			Ok(Err(pe)) => Err(lift_plugin_error(pe)),
			Err(e) => Err(PluginError::Trap(e.to_string())),
		}
	}

	async fn invoke_l4_bytes(
		&self,
		module_id: &ModuleId,
		export_name: &str,
		args_json: &str,
		input: L4BytesInput,
	) -> Result<L4BytesDecision, PluginError> {
		let key = module_id.0.as_ref().to_owned();

		let Some(component) = self.components.read().unwrap().get(&key).cloned() else {
			return Err(PluginError::Trap("module not loaded".into()));
		};

		let Some(meta) = self.metadata.read().unwrap().get(&key).cloned() else {
			return Err(PluginError::Trap("module not loaded".into()));
		};

		let Some(export_meta) = meta.exports.iter().find(|e| e.name == export_name) else {
			return Err(PluginError::Trap(format!("export '{export_name}' not found")));
		};

		if !export_meta.stateless {
			return Err(PluginError::Trap("stateful exports require StatefulPoolHandle".into()));
		}

		let skey = StatelessKey {
			module_id: key.clone(),
			export_name: export_name.to_owned(),
			args_json: args_json.to_owned(),
		};

		let pool = {
			let pools = self.stateless_pools.read().unwrap();
			pools.get(&skey).cloned()
		};

		let pool = if let Some(p) = pool {
			p
		} else {
			let new_pool = Arc::new(StatelessPool {
				component: Arc::clone(&component),
				args_json: args_json.to_owned(),
				construction_count: Arc::new(std::sync::atomic::AtomicU64::new(0)),
			});
			let mut pools = self.stateless_pools.write().unwrap();
			pools.entry(skey).or_insert(Arc::clone(&new_pool)).clone()
		};

		pool.construction_count.fetch_add(1, std::sync::atomic::Ordering::Relaxed);

		let host_state = HostState::new(args_json.to_owned(), Arc::clone(&self.fetch_backend));
		let mut store = Store::new(&self.engine, host_state);
		store.set_epoch_deadline(10);

		let plugin = match invoke_l4bytes::PluginL4BytesInvoke::instantiate_async(
			&mut store,
			&pool.component,
			&self.invoke_l4bytes_linker,
		)
		.await
		{
			Ok(p) => p,
			Err(e) => return Err(PluginError::Trap(e.to_string())),
		};

		let wit_input = lower_l4bytes_input(input);
		let result =
			plugin.vane_plugin_handler_l4_bytes().call_handle(&mut store, export_name, &wit_input);

		match result {
			Ok(Ok(d)) => Ok(lift_l4bytes_decision(d)),
			Ok(Err(pe)) => Err(lift_plugin_error_l4bytes(pe)?),
			Err(e) => Err(PluginError::Trap(e.to_string())),
		}
	}

	async fn invoke_l7_request(
		&self,
		module_id: &ModuleId,
		export_name: &str,
		args_json: &str,
		input: L7RequestInput,
	) -> Result<L7RequestDecision, PluginError> {
		let key = module_id.0.as_ref().to_owned();

		let Some(component) = self.components.read().unwrap().get(&key).cloned() else {
			return Err(PluginError::Trap("module not loaded".into()));
		};

		let Some(meta) = self.metadata.read().unwrap().get(&key).cloned() else {
			return Err(PluginError::Trap("module not loaded".into()));
		};

		let Some(export_meta) = meta.exports.iter().find(|e| e.name == export_name) else {
			return Err(PluginError::Trap(format!("export '{export_name}' not found")));
		};

		if !export_meta.stateless {
			return Err(PluginError::Trap("stateful exports require StatefulPoolHandle".into()));
		}

		let skey = StatelessKey {
			module_id: key.clone(),
			export_name: export_name.to_owned(),
			args_json: args_json.to_owned(),
		};

		let pool = {
			let pools = self.stateless_pools.read().unwrap();
			pools.get(&skey).cloned()
		};

		let pool = if let Some(p) = pool {
			p
		} else {
			let new_pool = Arc::new(StatelessPool {
				component: Arc::clone(&component),
				args_json: args_json.to_owned(),
				construction_count: Arc::new(std::sync::atomic::AtomicU64::new(0)),
			});
			let mut pools = self.stateless_pools.write().unwrap();
			pools.entry(skey).or_insert(Arc::clone(&new_pool)).clone()
		};

		pool.construction_count.fetch_add(1, std::sync::atomic::Ordering::Relaxed);

		let host_state = HostState::new(args_json.to_owned(), Arc::clone(&self.fetch_backend));
		let mut store = Store::new(&self.engine, host_state);
		store.set_epoch_deadline(10);

		let plugin = match invoke_l7request::PluginL7RequestInvoke::instantiate_async(
			&mut store,
			&pool.component,
			&self.invoke_l7request_linker,
		)
		.await
		{
			Ok(p) => p,
			Err(e) => return Err(PluginError::Trap(e.to_string())),
		};

		let wit_input = lower_l7request_input(input);
		let result =
			plugin.vane_plugin_handler_l7_request().call_handle(&mut store, export_name, &wit_input);

		match result {
			Ok(Ok(d)) => lift_l7request_decision(d),
			Ok(Err(pe)) => Err(lift_plugin_error_l7request(pe)?),
			Err(e) => Err(PluginError::Trap(e.to_string())),
		}
	}

	async fn invoke_l7_response(
		&self,
		module_id: &ModuleId,
		export_name: &str,
		args_json: &str,
		input: L7ResponseInput,
	) -> Result<L7ResponseDecision, PluginError> {
		let key = module_id.0.as_ref().to_owned();

		let Some(component) = self.components.read().unwrap().get(&key).cloned() else {
			return Err(PluginError::Trap("module not loaded".into()));
		};

		let Some(meta) = self.metadata.read().unwrap().get(&key).cloned() else {
			return Err(PluginError::Trap("module not loaded".into()));
		};

		let Some(export_meta) = meta.exports.iter().find(|e| e.name == export_name) else {
			return Err(PluginError::Trap(format!("export '{export_name}' not found")));
		};

		if !export_meta.stateless {
			return Err(PluginError::Trap("stateful exports require StatefulPoolHandle".into()));
		}

		let skey = StatelessKey {
			module_id: key.clone(),
			export_name: export_name.to_owned(),
			args_json: args_json.to_owned(),
		};

		let pool = {
			let pools = self.stateless_pools.read().unwrap();
			pools.get(&skey).cloned()
		};

		let pool = if let Some(p) = pool {
			p
		} else {
			let new_pool = Arc::new(StatelessPool {
				component: Arc::clone(&component),
				args_json: args_json.to_owned(),
				construction_count: Arc::new(std::sync::atomic::AtomicU64::new(0)),
			});
			let mut pools = self.stateless_pools.write().unwrap();
			pools.entry(skey).or_insert(Arc::clone(&new_pool)).clone()
		};

		pool.construction_count.fetch_add(1, std::sync::atomic::Ordering::Relaxed);

		let host_state = HostState::new(args_json.to_owned(), Arc::clone(&self.fetch_backend));
		let mut store = Store::new(&self.engine, host_state);
		store.set_epoch_deadline(10);

		let plugin = match invoke_l7response::PluginL7ResponseInvoke::instantiate_async(
			&mut store,
			&pool.component,
			&self.invoke_l7response_linker,
		)
		.await
		{
			Ok(p) => p,
			Err(e) => return Err(PluginError::Trap(e.to_string())),
		};

		let wit_input = lower_l7response_input(input);
		let result =
			plugin.vane_plugin_handler_l7_response().call_handle(&mut store, export_name, &wit_input);

		match result {
			Ok(Ok(d)) => lift_l7response_decision(d),
			Ok(Err(pe)) => Err(lift_plugin_error_l7response(pe)?),
			Err(e) => Err(PluginError::Trap(e.to_string())),
		}
	}
}

// ─── engine construction ─────────────────────────────────────────────────────

fn build_engine(pool_cap: u32) -> wasmtime::Result<Engine> {
	let mut config = Config::new();
	config.epoch_interruption(true);

	let mut pool = PoolingAllocationConfig::default();
	pool.max_memory_size(1024 * 1024);
	pool.total_memories(pool_cap);
	pool.total_component_instances(pool_cap);
	config.allocation_strategy(pool);

	Engine::new(&config)
}

// ─── component loading ───────────────────────────────────────────────────────

fn hex_sha256(data: &[u8]) -> String {
	let mut h = Sha256::new();
	h.update(data);
	h.finalize().iter().fold(String::new(), |mut s, b| {
		use std::fmt::Write as _;
		let _ = write!(s, "{b:02x}");
		s
	})
}

fn load_or_compile(
	engine: &Engine,
	src: &Path,
	cache: &Path,
	bytes: &[u8],
) -> Result<Component, Error> {
	if cache.exists() {
		match unsafe { Component::deserialize_file(engine, cache) } {
			Ok(c) => {
				trace!("wasm cache hit: {cache:?}");
				return Ok(c);
			}
			Err(e) => {
				warn!("wasm cache deserialize failed, recompiling: {e}");
			}
		}
	}

	let component = Component::from_binary(engine, bytes)
		.map_err(|e| Error::internal(format!("compile {}: {e}", src.display())))?;

	if let Ok(()) = std::fs::create_dir_all(CWASM_CACHE_DIR) {
		match component.serialize() {
			Ok(cwasm) => {
				if let Err(e) = std::fs::write(cache, &cwasm) {
					warn!("wasm cache write failed ({cache:?}): {e}");
				}
			}
			Err(e) => warn!("wasm serialize failed: {e}"),
		}
	}

	Ok(component)
}

// ─── metadata extraction ─────────────────────────────────────────────────────

async fn get_metadata(
	engine: &Engine,
	component: &Component,
	fetch_backend: Arc<dyn HttpFetchBackend>,
) -> Result<Arc<PluginMetadata>, Error> {
	let mut linker = Linker::<HostState>::new(engine);
	Plugin::add_to_linker::<HostState, HasSelf<HostState>>(&mut linker, |x| x)
		.map_err(|e| Error::internal(format!("linker setup: {e}")))?;

	let host_state = HostState::new(String::new(), fetch_backend);
	let mut store = Store::new(engine, host_state);
	// Allow up to 1000 ticks (≈1 s at 1 ms interval) for metadata loading.
	store.set_epoch_deadline(1000);

	let plugin = Plugin::instantiate_async(&mut store, component, &linker)
		.await
		.map_err(|e| Error::internal(format!("instantiate: {e}")))?;

	let raw = plugin
		.vane_plugin_registry()
		.call_get_metadata(&mut store)
		.map_err(|e| Error::internal(format!("get-metadata: {e}")))?;

	parse_metadata(raw)
}

// ─── handler-kind validation ─────────────────────────────────────────────────

// For each metadata export claiming kind K, confirm the component actually
// exports the corresponding handler interface at the component type level.
// This runs before any instantiation so the check is purely type-level.
fn validate_handler_exports(
	engine: &Engine,
	component: &Component,
	exports: &[PluginExport],
) -> Result<(), Error> {
	let comp_type = component.component_type();
	for export in exports {
		let iface = match export.kind {
			MiddlewareKind::L4Peek => "vane:plugin/handler-l4-peek@0.1.0",
			MiddlewareKind::L4Bytes => "vane:plugin/handler-l4-bytes@0.1.0",
			MiddlewareKind::L7Request => "vane:plugin/handler-l7-request@0.1.0",
			MiddlewareKind::L7Response => "vane:plugin/handler-l7-response@0.1.0",
		};
		if comp_type.get_export(engine, iface).is_none() {
			return Err(Error::internal(format!(
				"export '{}' declares kind '{}' but component does not export handler interface '{iface}'",
				export.name,
				kind_str(export.kind),
			)));
		}
	}
	Ok(())
}

fn kind_str(kind: MiddlewareKind) -> &'static str {
	match kind {
		MiddlewareKind::L4Peek => "l4-peek",
		MiddlewareKind::L4Bytes => "l4-bytes",
		MiddlewareKind::L7Request => "l7-request",
		MiddlewareKind::L7Response => "l7-response",
	}
}

fn parse_metadata(
	raw: exports::vane::plugin::registry::Metadata,
) -> Result<Arc<PluginMetadata>, Error> {
	// Validate abi-version major == ABI_MAJOR (0).
	let abi = &raw.abi_version;
	let major =
		abi.split('.').next().and_then(|s| s.parse::<u64>().ok()).ok_or_else(|| {
			Error::internal(format!("abi-version '{abi}' is not a valid semver string"))
		})?;
	if major != ABI_MAJOR {
		return Err(Error::internal(format!(
			"abi-version '{abi}' major {major} != expected {ABI_MAJOR}"
		)));
	}

	// Reject any export with needs-streaming-body: true.
	for exp in &raw.exports {
		if exp.needs_streaming_body {
			return Err(Error::internal(format!(
				"export '{}' sets needs-streaming-body: true, which is reserved in 0.1.0",
				exp.name
			)));
		}
	}

	// Reject duplicate export names.
	let mut seen = std::collections::HashSet::new();
	for exp in &raw.exports {
		if !seen.insert(exp.name.as_str()) {
			return Err(Error::internal(format!("duplicate export name '{}' in metadata", exp.name)));
		}
	}

	let exports = raw
		.exports
		.into_iter()
		.map(|e| {
			let kind = match e.kind {
				vane::plugin::types::MiddlewareKind::L4Peek => MiddlewareKind::L4Peek,
				vane::plugin::types::MiddlewareKind::L4Bytes => MiddlewareKind::L4Bytes,
				vane::plugin::types::MiddlewareKind::L7Request => MiddlewareKind::L7Request,
				vane::plugin::types::MiddlewareKind::L7Response => MiddlewareKind::L7Response,
			};
			PluginExport {
				name: e.name,
				kind,
				stateless: e.stateless,
				needs_body: e.needs_body,
				inspects: e.inspects,
			}
		})
		.collect();

	Ok(Arc::new(PluginMetadata {
		name: raw.name,
		version: raw.version,
		abi_version: raw.abi_version,
		exports,
	}))
}

// ─── tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
	use super::*;
	use async_trait::async_trait;

	struct MockFetch;

	#[async_trait]
	impl HttpFetchBackend for MockFetch {
		async fn fetch(
			&self,
			_req: HttpFetchRequest,
			_limits: HttpFetchLimits,
		) -> Result<vane_core::HttpFetchResponse, HttpFetchError> {
			Err(HttpFetchError::Internal("test".into()))
		}
	}

	fn mock_backend() -> Arc<dyn HttpFetchBackend> {
		Arc::new(MockFetch)
	}

	fn fixture_path() -> &'static Path {
		Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/metadata_fixture.wasm"))
	}

	async fn loaded_runtime() -> Arc<WasmtimeRuntime> {
		let rt = WasmtimeRuntime::new(mock_backend()).expect("runtime");
		rt.load_component(fixture_path()).await.expect("load_component");
		rt
	}

	fn fixture_module_id() -> ModuleId {
		ModuleId(Arc::from(fixture_path().to_string_lossy().as_ref()))
	}

	fn empty_input() -> L4PeekInput {
		L4PeekInput { peek: vec![1, 2, 3], context: vec![] }
	}

	// Verify the Engine builds and the epoch ticker starts without panicking.
	// This exercises `build_engine` + the tokio::spawn path inside `new`.
	#[tokio::test]
	async fn runtime_new_constructs_engine_and_starts_ticker() {
		let rt = WasmtimeRuntime::new(mock_backend()).expect("WasmtimeRuntime::new");
		// Yield to let the ticker task run at least once.
		tokio::time::sleep(Duration::from_millis(5)).await;
		// The epoch counter is an internal Engine state; we can't read it directly,
		// but if the ticker panicked the task would be aborted and `rt` would still
		// be valid (abort_handle is already set). Existence of `rt` is enough.
		drop(rt);
	}

	// load_component must return a typed error for a missing file.
	#[tokio::test]
	async fn load_component_missing_file_returns_error() {
		let rt = WasmtimeRuntime::new(mock_backend()).expect("runtime");
		let err =
			rt.load_component(Path::new("/nonexistent/plugin.wasm")).await.expect_err("must fail");
		assert!(err.to_string().contains("read"), "error should mention read: {err}");
	}

	// load_component must return a typed error for a file that is not a WASM component.
	#[tokio::test]
	async fn load_component_invalid_bytes_returns_error() {
		let dir = tempfile::tempdir().expect("tempdir");
		let path = dir.path().join("bad.wasm");
		std::fs::write(&path, b"not wasm at all").expect("write");
		let rt = WasmtimeRuntime::new(mock_backend()).expect("runtime");
		let err = rt.load_component(&path).await.expect_err("must fail");
		assert!(err.to_string().contains("compile"), "error should mention compile: {err}");
	}

	// parse_metadata rejects an abi-version with wrong major.
	#[test]
	fn parse_metadata_rejects_wrong_abi_major() {
		let raw = exports::vane::plugin::registry::Metadata {
			name: "test".into(),
			version: "1.0.0".into(),
			abi_version: "1.0.0".into(), // major=1, expected 0
			exports: vec![],
		};
		let err = parse_metadata(raw).expect_err("must reject");
		assert!(err.to_string().contains("major"), "{err}");
	}

	// parse_metadata rejects needs-streaming-body: true.
	#[test]
	fn parse_metadata_rejects_streaming_body() {
		let raw = exports::vane::plugin::registry::Metadata {
			name: "test".into(),
			version: "1.0.0".into(),
			abi_version: "0.1.0".into(),
			exports: vec![vane::plugin::types::MiddlewareExport {
				name: "e".into(),
				kind: vane::plugin::types::MiddlewareKind::L7Request,
				stateless: true,
				needs_body: false,
				inspects: vec![],
				needs_streaming_body: true,
			}],
		};
		let err = parse_metadata(raw).expect_err("must reject");
		assert!(err.to_string().contains("streaming"), "{err}");
	}

	// parse_metadata rejects duplicate export names.
	#[test]
	fn parse_metadata_rejects_duplicate_export_names() {
		let export = || vane::plugin::types::MiddlewareExport {
			name: "dup".into(),
			kind: vane::plugin::types::MiddlewareKind::L7Request,
			stateless: true,
			needs_body: false,
			inspects: vec![],
			needs_streaming_body: false,
		};
		let raw = exports::vane::plugin::registry::Metadata {
			name: "test".into(),
			version: "1.0.0".into(),
			abi_version: "0.1.0".into(),
			exports: vec![export(), export()],
		};
		let err = parse_metadata(raw).expect_err("must reject");
		assert!(err.to_string().contains("duplicate"), "{err}");
	}

	// parse_metadata correctly maps all four MiddlewareKind variants.
	#[test]
	fn parse_metadata_maps_all_middleware_kinds() {
		use vane::plugin::types::MiddlewareKind as WitKind;
		for (wit, expected) in [
			(WitKind::L4Peek, MiddlewareKind::L4Peek),
			(WitKind::L4Bytes, MiddlewareKind::L4Bytes),
			(WitKind::L7Request, MiddlewareKind::L7Request),
			(WitKind::L7Response, MiddlewareKind::L7Response),
		] {
			let raw = exports::vane::plugin::registry::Metadata {
				name: "p".into(),
				version: "0.1.0".into(),
				abi_version: "0.1.0".into(),
				exports: vec![vane::plugin::types::MiddlewareExport {
					name: "e".into(),
					kind: wit,
					stateless: true,
					needs_body: false,
					inspects: vec![],
					needs_streaming_body: false,
				}],
			};
			let meta = parse_metadata(raw).expect("parse");
			assert_eq!(meta.exports[0].kind, expected);
		}
	}

	// Smoke test: load the fixture component generated by build.rs and verify
	// that the metadata round-trips through the canonical ABI correctly.
	#[tokio::test]
	async fn smoke_load_metadata_fixture() {
		let fixture = fixture_path();
		assert!(fixture.exists(), "fixture not found; re-run cargo build to regenerate");

		let rt = WasmtimeRuntime::new(mock_backend()).expect("runtime");
		let meta = rt.load_component(fixture).await.expect("load_component");

		assert_eq!(meta.name, "fixture");
		assert_eq!(meta.abi_version, "0.1.0");
		assert_eq!(meta.exports.len(), 1);
		assert_eq!(meta.exports[0].name, "probe");
		assert_eq!(meta.exports[0].kind, MiddlewareKind::L4Peek);
		assert!(meta.exports[0].stateless);
	}

	// load_component must reject a component whose metadata claims kind K but the
	// component binary does not export the corresponding handler interface.
	#[tokio::test]
	async fn load_component_rejects_missing_handler_interface() {
		let fixture = Path::new(concat!(env!("CARGO_MANIFEST_DIR"), "/fixtures/mismatch_fixture.wasm"));
		assert!(fixture.exists(), "mismatch fixture not found; re-run cargo build to regenerate");

		let rt = WasmtimeRuntime::new(mock_backend()).expect("runtime");
		let err = rt.load_component(fixture).await.expect_err("must reject mismatch");
		let msg = err.to_string();
		assert!(
			msg.contains("handler") || msg.contains("l4-peek"),
			"error should mention the missing handler: {msg}",
		);
	}

	// Stateless rental always sees fresh linear memory: counter is zero on each call.
	// Both invocations must return Continue because memory resets on every rental.
	#[tokio::test]
	async fn stateless_pool_fresh_memory_per_rental() {
		let rt = loaded_runtime().await;
		let mid = fixture_module_id();

		let r1 = rt.invoke_l4_peek(&mid, "probe", "{}", empty_input()).await;
		assert!(matches!(r1, Ok(L4PeekDecision::Continue)), "first should be Continue");

		let r2 = rt.invoke_l4_peek(&mid, "probe", "{}", empty_input()).await;
		assert!(
			matches!(r2, Ok(L4PeekDecision::Continue)),
			"second should also be Continue (fresh memory)"
		);
	}

	// With a pool cap of 2, instantiate two plugins directly and hold the
	// stores open. A subsequent invocation must trap because the
	// PoolingAllocator has no free component-instance slots. Spawning a
	// fixed number of concurrent invocations and hoping at least one of
	// them races inside `instantiate_async` is racy under light load —
	// rentals returned to the pool faster than the next task arrived.
	// Holding rentals explicitly removes the timing dependency entirely.
	#[tokio::test(flavor = "multi_thread")]
	async fn stateless_pool_exhaustion_returns_overload_error() {
		let rt = WasmtimeRuntime::new_with_pool_cap(mock_backend(), 2).expect("runtime");
		rt.load_component(fixture_path()).await.expect("load");
		let mid = fixture_module_id();

		let component = rt
			.components
			.read()
			.unwrap()
			.get(mid.0.as_ref())
			.cloned()
			.expect("fixture component must be loaded");

		// Directly instantiate two plugins so they each occupy a pool slot.
		// Both stores stay alive through the subsequent invocation attempt,
		// which must trap because no component-instance slot is available.
		let mut store_a =
			Store::new(&rt.engine, HostState::new("{}".to_owned(), Arc::clone(&rt.fetch_backend)));
		store_a.set_epoch_deadline(10);
		let plugin_a = invoke_l4peek::PluginL4PeekInvoke::instantiate_async(
			&mut store_a,
			&component,
			&rt.invoke_linker,
		)
		.await
		.expect("first rental must succeed");

		let mut store_b =
			Store::new(&rt.engine, HostState::new("{}".to_owned(), Arc::clone(&rt.fetch_backend)));
		store_b.set_epoch_deadline(10);
		let plugin_b = invoke_l4peek::PluginL4PeekInvoke::instantiate_async(
			&mut store_b,
			&component,
			&rt.invoke_linker,
		)
		.await
		.expect("second rental must succeed");

		let result = rt.invoke_l4_peek(&mid, "probe", "{}", empty_input()).await;
		assert!(
			matches!(result, Err(PluginError::Trap(_))),
			"third invocation must trap when both pool slots are held: {result:?}",
		);

		// Keep the rentals alive past the assertion so the pool stays
		// saturated for the duration of the third invocation.
		let _keepalive = (plugin_a, store_a, plugin_b, store_b);
	}

	// Stateful pool preserves linear memory between invocations:
	// first call writes counter=42 → Continue; second call sees counter!=0 → Close.
	#[tokio::test]
	async fn stateful_pool_persists_state_across_invocations() {
		let rt = loaded_runtime().await;
		let mid = fixture_module_id();

		let pool = rt.create_stateful_pool(&mid, "probe", "{}", 1).await.expect("create_stateful_pool");

		let r1 = pool.invoke_l4_peek("probe", empty_input()).await;
		assert!(matches!(r1, Ok(L4PeekDecision::Continue)), "first call should be Continue: {r1:?}");

		let r2 = pool.invoke_l4_peek("probe", empty_input()).await;
		assert!(
			matches!(r2, Ok(L4PeekDecision::Close)),
			"second call should be Close (state persists): {r2:?}"
		);
	}

	// A pool of N=1 with both slots checked out returns Exhausted immediately.
	#[tokio::test(flavor = "multi_thread")]
	async fn stateful_pool_exhaustion_no_queueing() {
		let rt = loaded_runtime().await;
		let mid = fixture_module_id();

		let pool = rt.create_stateful_pool(&mid, "probe", "{}", 1).await.expect("create_stateful_pool");

		// Drain the single slot by popping it directly.
		let _instance = pool.instances.lock().unwrap().pop().expect("instance");

		let start = std::time::Instant::now();
		let result = pool.invoke_l4_peek("probe", empty_input()).await;
		let elapsed = start.elapsed();

		assert!(matches!(result, Err(PluginError::Exhausted)), "should be Exhausted: {result:?}");
		assert!(elapsed.as_millis() < 50, "should return immediately, took {elapsed:?}");
	}

	// Dropping pool1 and creating pool2 yields fresh state: both first invocations
	// return Continue because each pool has its own instance with zeroed memory.
	#[tokio::test]
	async fn stateful_pool_reload_fresh_state() {
		let rt = loaded_runtime().await;
		let mid = fixture_module_id();

		let pool1 = rt.create_stateful_pool(&mid, "probe", "{}", 1).await.expect("pool1");
		let r1 = pool1.invoke_l4_peek("probe", empty_input()).await;
		assert!(matches!(r1, Ok(L4PeekDecision::Continue)), "pool1 first: {r1:?}");
		drop(pool1);

		let pool2 = rt.create_stateful_pool(&mid, "probe", "{}", 1).await.expect("pool2");
		let r2 = pool2.invoke_l4_peek("probe", empty_input()).await;
		assert!(
			matches!(r2, Ok(L4PeekDecision::Continue)),
			"pool2 first should also be Continue: {r2:?}"
		);
	}

	// Two invocations with the same key share one StatelessPool entry.
	// The construction_count must equal 2 after two rentals.
	#[tokio::test]
	async fn stateless_dedup_shares_construction_count() {
		let rt = loaded_runtime().await;
		let mid = fixture_module_id();

		rt.invoke_l4_peek(&mid, "probe", "{}", empty_input()).await.expect("first");
		rt.invoke_l4_peek(&mid, "probe", "{}", empty_input()).await.expect("second");

		let skey = StatelessKey {
			module_id: fixture_path().to_string_lossy().into_owned(),
			export_name: "probe".into(),
			args_json: "{}".into(),
		};
		let pools = rt.stateless_pools.read().unwrap();
		let pool = pools.get(&skey).expect("pool should exist");
		let count = pool.construction_count.load(std::sync::atomic::Ordering::Relaxed);
		assert_eq!(count, 2, "expected construction_count=2, got {count}");
	}

	// Two invocations with distinct args_json are tracked as separate pool entries.
	// Both must succeed, confirming the key includes args_json.
	#[tokio::test]
	async fn distinct_args_produce_distinct_dedup_entries() {
		let rt = loaded_runtime().await;
		let mid = fixture_module_id();

		rt.invoke_l4_peek(&mid, "probe", r#"{"test":true}"#, empty_input())
			.await
			.expect("invoke with args A");
		rt.invoke_l4_peek(&mid, "probe", r#"{"other":1}"#, empty_input())
			.await
			.expect("invoke with args B");

		let pools = rt.stateless_pools.read().unwrap();
		assert_eq!(
			pools.len(),
			2,
			"distinct args_json should produce two separate pool entries; got {}",
			pools.len()
		);
	}

	// Verifies the host-side get-args implementation: the function returns the args
	// string that was bound to the store at creation time, and sets args_received.
	// The ComponentEncoder pipeline (embed_component_metadata + ComponentEncoder)
	// cannot generate canonical ABI adapters for core-module host imports from bare
	// WAT; this test therefore drives the host function directly, which covers the
	// same host-side contract that real WIT plugins exercise via the component ABI.
	#[tokio::test]
	async fn host_get_args_returns_bound_args_to_plugin() {
		let args = r#"{"mode":"test"}"#;
		let mut state = HostState::new(args.to_owned(), mock_backend());

		let received = invoke_l4peek::vane::host::host::Host::get_args(&mut state).await.unwrap();
		assert_eq!(received, args, "get-args must return the bound args string");
		assert_eq!(
			state.args_received.as_deref(),
			Some(args),
			"args_received must be set after get-args is called"
		);
	}

	// ─── validate_status ────────────────────────────────────────────────────────

	#[test]
	fn validate_status_accepts_boundary_values() {
		assert!(validate_status(100).is_ok());
		assert!(validate_status(599).is_ok());
		assert!(validate_status(200).is_ok());
		assert!(validate_status(404).is_ok());
	}

	#[test]
	fn validate_status_rejects_out_of_range() {
		assert!(validate_status(99).is_err());
		assert!(validate_status(600).is_err());
		assert!(validate_status(0).is_err());
	}

	// ─── validate_header_name ───────────────────────────────────────────────────

	#[test]
	fn validate_header_name_accepts_clean_ascii() {
		assert!(validate_header_name("content-type").is_ok());
		assert!(validate_header_name("x-custom-header").is_ok());
	}

	#[test]
	fn validate_header_name_rejects_cr() {
		assert!(validate_header_name("bad\rheader").is_err());
	}

	#[test]
	fn validate_header_name_rejects_lf() {
		assert!(validate_header_name("bad\nheader").is_err());
	}

	#[test]
	fn validate_header_name_rejects_nul() {
		assert!(validate_header_name("bad\0header").is_err());
	}

	// ─── validate_header_value ──────────────────────────────────────────────────

	#[test]
	fn validate_header_value_accepts_clean_ascii() {
		assert!(validate_header_value("application/json").is_ok());
		assert!(validate_header_value("Bearer token123").is_ok());
	}

	#[test]
	fn validate_header_value_rejects_cr() {
		assert!(validate_header_value("bad\rvalue").is_err());
	}

	#[test]
	fn validate_header_value_rejects_lf() {
		assert!(validate_header_value("bad\nvalue").is_err());
	}

	#[test]
	fn validate_header_value_rejects_nul() {
		assert!(validate_header_value("bad\0value").is_err());
	}

	// ─── validate_on_error_hint ─────────────────────────────────────────────────

	#[test]
	fn validate_on_error_hint_accepts_none() {
		assert!(validate_on_error_hint(None).is_ok());
	}

	#[test]
	fn validate_on_error_hint_accepts_force_close() {
		assert!(validate_on_error_hint(Some(&"force-close".to_owned())).is_ok());
	}

	#[test]
	fn validate_on_error_hint_accepts_internal() {
		assert!(validate_on_error_hint(Some(&"internal".to_owned())).is_ok());
	}

	#[test]
	fn validate_on_error_hint_rejects_empty_string() {
		assert!(validate_on_error_hint(Some(&String::new())).is_err());
	}

	#[test]
	fn validate_on_error_hint_rejects_unknown_value() {
		assert!(validate_on_error_hint(Some(&"retry".to_owned())).is_err());
		assert!(validate_on_error_hint(Some(&"pass-through".to_owned())).is_err());
	}
}
