name: Docs Check

on:
  pull_request:
    branches: ['latest']
  workflow_dispatch:

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        working-directory: docs
        run: bun run lint

      - name: Check Formatting
        run: npx prettier --check .

      - name: Build
        working-directory: docs
        run: bun run build
