name: Publish to crates.io

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build and release (e.g., v{a.b.c})'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for Trusted Publishing

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || inputs.tag || github.ref_name }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake clang

      - name: Publish to Crates.io
        env:
          CC: clang
          CXX: clang++
        run: cargo publish
