name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: test

      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Test
        run: cargo nextest run --workspace --no-fail-fast
